### ISSUE TITLE
error on docker-compose up while calling kibana on 6501- Exception in Thread 7

### ISSUE THREAD

**Issue by mattmeye** [deviantony/docker-elk#102]
**edit**: SRY, my mistake - my instance need a lot of time to start kibana
pls remove this issue

---

Hello, i testet docker-elk successfully on my dev-mashine and wanted to install an elk on amazon aws but i get an error, when i call  http port 6501 on my instance.

System:
CenOS 7 on Amazon AWS t2.medium
- run yum update, install docker python-pip git, set selinux to permissive
- create directory /root/docker
- git clone docker-elk into /root/docker
- run docker-compose up in /root/docker/docker-elk

full log of docker-compose: http://pastebin.com/x3Cj4xaD

error:

```
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/compose/cli/log_printer.py", line 197, in watch_events
    for event in event_stream:
  File "/usr/lib/python2.7/site-packages/compose/project.py", line 356, in events
    decode=True
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 290, in _stream_helper
    for chunk in json_stream(self._stream_helper(response, False)):
  File "/usr/lib/python2.7/site-packages/docker/utils/json_stream.py", line 66, in split_buffer
    for data in stream_as_text(stream):
  File "/usr/lib/python2.7/site-packages/docker/utils/json_stream.py", line 22, in stream_as_text
    for data in stream:
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 296, in _stream_helper
    data = reader.read(1)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 324, in read
    flush_decoder = True
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 237, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.
```

Can someone help?

**Comment by antoineco** [comment]
Looks like the Docker Engine daemon crashed so docker-compose threw a `ReadTimeoutError` exception.

Could you confirm that by issuing some commands from the Docker client? eg. `docker info`

**Comment by antoineco** [comment]
@mattmeye feel free to close this issue is you sorted it out ;)
