### ISSUE TITLE
logstash... Address in use {:host=>"0.0.0.0", :port=>5000}

### ISSUE THREAD

**Issue by mireczatko** [deviantony/docker-elk#109]
logstash container first run produces:
```
logstash_1       | 16:12:14.320 [[main]-pipeline-manager] INFO  logstash.inputs.tcp - Starting tcp input listener {:address=>"0.0.0.0:5000"}
logstash_1       | 16:12:14.347 [[main]-pipeline-manager] INFO  logstash.inputs.tcp - Starting tcp input listener {:address=>"0.0.0.0:5000"}
logstash_1       | 16:12:14.349 [[main]-pipeline-manager] ERROR logstash.inputs.tcp - Could not start TCP server: Address in use {:host=>"0.0.0.0", :port=>5000}
logstash_1       | 16:12:14.350 [[main]-pipeline-manager] ERROR logstash.pipeline - Error registering plugin {:plugin=>"<LogStash::Inputs::Tcp port=>5000, id=>\"6daac4ada47edb10ed11af15cbbf99365c6490ec-5\", enable_metric=>true, codec=><LogStash::Codecs::Line id=>\"line_69ca403c-935e-495b-9124-398fad87342e\", enable_metric=>true, charset=>\"UTF-8\", delimiter=>\"\\n\">, host=>\"0.0.0.0\", data_timeout=>-1, mode=>\"server\", proxy_protocol=>false, ssl_enable=>false, ssl_verify=>true, ssl_key_passphrase=><password>>", :error=>"Address already in use - bind - Address already in use"}
logstash_1       | 16:12:15.373 [[main]-pipeline-manager] ERROR logstash.agent - Pipeline aborted due to error {:exception=>#<Errno::EADDRINUSE: Address already in use - bind - Address already in use>, :backtrace=>["org/jruby/ext/socket/RubyTCPServer.java:118:in `initialize'", "org/jruby/RubyIO.java:871:in `new'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-4.1.0/lib/logstash/inputs/tcp.rb:279:in `new_server_socket'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-4.1.0/lib/logstash/inputs/tcp.rb:89:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:282:in `register_plugin'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:293:in `register_plugins'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:293:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:436:in `start_inputs'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:337:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:232:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:387:in `start_pipeline'"]}
logstash_1       | 16:12:15.491 [Api Webserver] INFO  logstash.agent - Successfully started Logstash API endpoint {:port=>9600}
logstash_1       | 16:12:18.388 [LogStash::Runner] WARN  logstash.agent - stopping pipeline {:id=>"main"}
dockerelk_logstash_1 exited with code 0
```
As it is separated container, nothing can occupy this port. To be on a safe side I scaned host machine ports and port 5000 is free
what can be behind? Any ideas?
Maybe main problem could be: **docker4windows Version 17.03.1-ce-win5 (10743)**

**Comment by antoineco** [comment]
One of your inputs is defined twice (look at the first 2 lines), make sure you don't have a duplicate either in `logstash/config` or `logstash/pipeline`.

**Comment by mireczatko** [comment]
thank you very much @antoineco, I noticed it right after I posted the issue. Of course, this is my fault, I somehow created "logstash - Copy.conf" file

**Comment by antoineco** [comment]
Glad you figured it out (y)
