### ISSUE TITLE
unknown setting [searchguard.ssl.transport.truststore_filepath]

### ISSUE THREAD

**Issue by Toub** [deviantony/docker-elk#168]
With last version of searchguard branch, I get the following elasticsearch error after docker-compose run:
```
[2017-09-07T08:50:41,121][INFO ][o.e.n.Node               ] [] initializing ...
[2017-09-07T08:50:41,225][INFO ][o.e.e.NodeEnvironment    ] [TFSPlaR] using [1] data paths, mounts [[/ (overlay)]], net usable_space [298.7gb], net total_space [452.1gb], spins? [possibly], types [overlay]
[2017-09-07T08:50:41,225][INFO ][o.e.e.NodeEnvironment    ] [TFSPlaR] heap size [247.5mb], compressed ordinary object pointers [true]
[2017-09-07T08:50:41,227][INFO ][o.e.n.Node               ] node name [TFSPlaR] derived from node ID [TFSPlaR-QUaaKUOqVjj1Zg]; set [node.name] to override
[2017-09-07T08:50:41,227][INFO ][o.e.n.Node               ] version[5.5.2], pid[1], build[b2f0c09/2017-08-14T12:33:14.154Z], OS[Linux/4.9.0-3-amd64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_141/25.141-b16]
[2017-09-07T08:50:41,227][INFO ][o.e.n.Node               ] JVM arguments [-Xms2g, -Xmx2g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.cgroups.hierarchy.override=/, -Xmx256m, -Xms256m, -Des.path.home=/usr/share/elasticsearch]
[2017-09-07T08:50:44,114][INFO ][o.e.p.PluginsService     ] [TFSPlaR] loaded module [aggs-matrix-stats]
[2017-09-07T08:50:44,114][INFO ][o.e.p.PluginsService     ] [TFSPlaR] loaded module [ingest-common]
[2017-09-07T08:50:44,117][INFO ][o.e.p.PluginsService     ] [TFSPlaR] loaded module [lang-expression]
[2017-09-07T08:50:44,117][INFO ][o.e.p.PluginsService     ] [TFSPlaR] loaded module [lang-groovy]
[2017-09-07T08:50:44,117][INFO ][o.e.p.PluginsService     ] [TFSPlaR] loaded module [lang-mustache]
[2017-09-07T08:50:44,117][INFO ][o.e.p.PluginsService     ] [TFSPlaR] loaded module [lang-painless]
[2017-09-07T08:50:44,117][INFO ][o.e.p.PluginsService     ] [TFSPlaR] loaded module [parent-join]
[2017-09-07T08:50:44,117][INFO ][o.e.p.PluginsService     ] [TFSPlaR] loaded module [percolator]
[2017-09-07T08:50:44,117][INFO ][o.e.p.PluginsService     ] [TFSPlaR] loaded module [reindex]
[2017-09-07T08:50:44,117][INFO ][o.e.p.PluginsService     ] [TFSPlaR] loaded module [transport-netty3]
[2017-09-07T08:50:44,118][INFO ][o.e.p.PluginsService     ] [TFSPlaR] loaded module [transport-netty4]
[2017-09-07T08:50:44,118][INFO ][o.e.p.PluginsService     ] [TFSPlaR] loaded plugin [ingest-geoip]
[2017-09-07T08:50:44,119][INFO ][o.e.p.PluginsService     ] [TFSPlaR] loaded plugin [ingest-user-agent]
[2017-09-07T08:50:44,119][INFO ][o.e.p.PluginsService     ] [TFSPlaR] loaded plugin [x-pack]
[2017-09-07T08:50:46,210][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [searchguard.authcz.admin_dn.0] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.5.2.jar:5.5.2]
Caused by: java.lang.IllegalArgumentException: unknown setting [searchguard.authcz.admin_dn.0] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:293) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:256) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:139) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.node.Node.<init>(Node.java:343) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.node.Node.<init>(Node.java:244) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:232) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:232) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:351) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.5.2.jar:5.5.2]
	... 6 more
	Suppressed: java.lang.IllegalArgumentException: unknown setting [searchguard.ssl.transport.enforce_hostname_verification] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
		at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:293) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:256) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:139) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.node.Node.<init>(Node.java:343) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.node.Node.<init>(Node.java:244) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:232) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:232) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:351) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.5.2.jar:5.5.2]
	Suppressed: java.lang.IllegalArgumentException: unknown setting [searchguard.ssl.transport.keystore_filepath] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
		at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:293) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:256) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:139) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.node.Node.<init>(Node.java:343) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.node.Node.<init>(Node.java:244) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:232) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:232) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:351) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.5.2.jar:5.5.2]
	Suppressed: java.lang.IllegalArgumentException: unknown setting [searchguard.ssl.transport.truststore_filepath] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
		at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:293) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:256) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:139) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.node.Node.<init>(Node.java:343) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.node.Node.<init>(Node.java:244) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:232) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:232) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:351) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.5.2.jar:5.5.2]
		at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.5.2.jar:5.5.2]
```

**Comment by floragunncom** [comment]
Thats because the Search Guard plugin is not loaded at all.

**Comment by antoineco** [comment]
You probably built `master` before building `searchguard`. `docker-compose build` should fix that.

**Comment by Toub** [comment]
Right!
@antoineco solutions worked.

Thanks guys!
