### ISSUE TITLE
Issue with scaling the cluster

### ISSUE THREAD

**Issue by liamptk** [deviantony/docker-elk#228]
I've followed the wiki instructions for scaling out my cluster, but when running the command i'm encountering this...

Error
```
[2018-01-12T15:17:04,679][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [[/usr/share/elasticsearch/data/docker-cluster]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:134) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:121) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:69) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.0.0.jar:6.0.0]
```

Elasticsearch.yml
```
## Default Elasticsearch configuration from elasticsearch-docker.
## from https://github.com/elastic/elasticsearch-docker/blob/master/build/elasticsearch/elasticsearch.yml
#
cluster.name: "docker-cluster"
network.host: 0.0.0.0

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1

## Use single node discovery in order to disable production mode and avoid bootstrap checks
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
#
#discovery.type: single-node
discovery.type: zen
discovery.zen.ping.unicast.hosts: elasticsearch

## Disable X-Pack
## see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
##     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
#
xpack.security.enabled: false
xpack.monitoring.enabled: false
xpack.ml.enabled: false
xpack.graph.enabled: false
xpack.watcher.enabled: false
```

Docker-compose.yml
```
version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200"
      - "9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: zen
      discovery.zen.ping.unicast.hosts: elasticsearch
    networks: 
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstash/logstash.crt:/etc/server.crt
      - ./logstash/logstash.key:/etc/server.key
 
    ports:
      - "5000:5000"
      - "5044:5044"
      - "5045:5045"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge
```

**Comment by antoineco** [comment]
That's because every node is mounting the same data directory from your host, so they're competing for it. 

Delete the data volume definition from the `elasticsearch` service to let Docker deal with it. After that you'll see 3 new volumes listed when you types `docker volume ls`.

**Comment by antoineco** [comment]
Oh, the answer is actually in the error message :)

Bump the value of the `node.max_local_storage_nodes` property to something large enough that you won't hit the limit.

Ref. https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#max-local-storage-nodes

**Comment by liamptk** [comment]
Thanks for your feedback Sir, golden as always. Do you have any recommendation on how to scale a docker setup for production? The idea of having multiple nodes on one cluster doesn't seem wise for anything other than testing. Is it possible to horizontally scale the es cluster across other EC2 instances?

**Comment by antoineco** [comment]
@liamptk happy to help :+1:

There are many ways to design a resilient ES cluster with/without multiple node roles (master, client, data versus all-in-one node). Docker Compose unfortunately doesn't allow scaling across multiple zones, unless your docker client is configured to talk to a Swarm cluster.

Although these two resources are centered around Kubernetes I'd really recommend to take a look at them for grasping concepts and reading configuration examples:

* https://github.com/pires/kubernetes-elasticsearch-cluster
* https://github.com/kubernetes/charts/blob/master/incubator/elasticsearch/README.md

The official ES documentation is also full of useful information.
