### ISSUE TITLE
Elasticsearch 5.5.0 data with Elasticsearch 6.1.0

### ISSUE THREAD

**Issue by lucasmello** [deviantony/docker-elk#235]
I was using Elasticsearch 5.5.0 with mounted volumes (/data/elasticsearch:/usr/share/elasticsearch/data/) with Docker Swarm. Everything was just working, but now I started using Elasticsearch 6.1.0 with Searchguard, and tried to mount the same directories, but Elasticsearch is not working. 

When I don't mount the volumes, everything works!

I got this error:

`org.elasticsearch.action.FailedNodeException: Failed node [9Op6RiwgQmWYQcSLc6zEUw]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.onFailure(TransportNodesAction.java:239) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.access$200(TransportNodesAction.java:153) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleException(TransportNodesAction.java:211) [elasticsearch-6.1.0.jar:6.1.0]
        at com.floragunn.searchguard.transport.SearchGuardInterceptor$RestoringTransportResponseHandler.handleException(SearchGuardInterceptor.java:191) [search-guard-6-6.1.0-20.1.jar:6.1.0-20.1]
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1056) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1149) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1133) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.transport.TransportService$7.onFailure(TransportService.java:663) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:622) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) [elasticsearch-6.1.0.jar:6.1.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: org.elasticsearch.transport.RemoteTransportException: [9Op6Riw][10.0.0.21:9300][internal:gateway/local/started_shards[n]]
Caused by: org.elasticsearch.ElasticsearchException: failed to load started shards
        at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:171) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:62) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:140) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:262) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:258) ~[elasticsearch-6.1.0.jar:6.1.0]
        at com.floragunn.searchguard.ssl.transport.SearchGuardSSLRequestHandler.messageReceivedDecorate(SearchGuardSSLRequestHandler.java:170) ~[?:?]
        at com.floragunn.searchguard.transport.SearchGuardRequestHandler.messageReceivedDecorate(SearchGuardRequestHandler.java:121) ~[?:?]
        at com.floragunn.searchguard.ssl.transport.SearchGuardSSLRequestHandler.messageReceived(SearchGuardSSLRequestHandler.java:92) ~[?:?]
        at com.floragunn.searchguard.SearchGuardPlugin$6$1.messageReceived(SearchGuardPlugin.java:525) ~[?:?]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:652) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:637) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.1.0.jar:6.1.0]
        ... 3 more
Caused by: org.elasticsearch.ElasticsearchException: java.io.IOException: failed to read [id:59, legacy:false, file:/usr/share/elasticsearch/data/nodes/0/indices/EIucaAJiQ9OQnHjzVO6X3A/_state/state-59.st]
        at org.elasticsearch.ExceptionsHelper.maybeThrowRuntimeAndSuppress(ExceptionsHelper.java:150) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:334) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:128) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:62) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:140) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:262) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:258) ~[elasticsearch-6.1.0.jar:6.1.0]
        at com.floragunn.searchguard.ssl.transport.SearchGuardSSLRequestHandler.messageReceivedDecorate(SearchGuardSSLRequestHandler.java:170) ~[?:?]
        at com.floragunn.searchguard.transport.SearchGuardRequestHandler.messageReceivedDecorate(SearchGuardRequestHandler.java:121) ~[?:?]
        at com.floragunn.searchguard.ssl.transport.SearchGuardSSLRequestHandler.messageReceived(SearchGuardSSLRequestHandler.java:92) ~[?:?]
        at com.floragunn.searchguard.SearchGuardPlugin$6$1.messageReceived(SearchGuardPlugin.java:525) ~[?:?]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:652) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:637) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.1.0.jar:6.1.0]
        ... 3 more
Caused by: java.io.IOException: failed to read [id:59, legacy:false, file:/usr/share/elasticsearch/data/nodes/0/indices/EIucaAJiQ9OQnHjzVO6X3A/_state/state-59.st]
        at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:327) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:128) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:62) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:140) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:262) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:258) ~[elasticsearch-6.1.0.jar:6.1.0]
        at com.floragunn.searchguard.ssl.transport.SearchGuardSSLRequestHandler.messageReceivedDecorate(SearchGuardSSLRequestHandler.java:170) ~[?:?]
        at com.floragunn.searchguard.transport.SearchGuardRequestHandler.messageReceivedDecorate(SearchGuardRequestHandler.java:121) ~[?:?]
        at com.floragunn.searchguard.ssl.transport.SearchGuardSSLRequestHandler.messageReceived(SearchGuardSSLRequestHandler.java:92) ~[?:?]
        at com.floragunn.searchguard.SearchGuardPlugin$6$1.messageReceived(SearchGuardPlugin.java:525) ~[?:?]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:652) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:637) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.1.0.jar:6.1.0]
        ... 3 more
Caused by: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/data/nodes/0/indices/EIucaAJiQ9OQnHjzVO6X3A/_state/state-59.st
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:?]
        at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_151]
        at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_151]
        at org.apache.lucene.store.SimpleFSDirectory.openInput(SimpleFSDirectory.java:77) ~[lucene-core-7.1.0.jar:7.1.0 84c90ad2c0218156c840e19a64d72b8a38550659 - ubuntu - 2017-10-13 16:12:42]
        at org.elasticsearch.gateway.MetaDataStateFormat.read(MetaDataStateFormat.java:187) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:322) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:128) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:62) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:140) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:262) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:258) ~[elasticsearch-6.1.0.jar:6.1.0]
        at com.floragunn.searchguard.ssl.transport.SearchGuardSSLRequestHandler.messageReceivedDecorate(SearchGuardSSLRequestHandler.java:170) ~[?:?]
        at com.floragunn.searchguard.transport.SearchGuardRequestHandler.messageReceivedDecorate(SearchGuardRequestHandler.java:121) ~[?:?]
        at com.floragunn.searchguard.ssl.transport.SearchGuardSSLRequestHandler.messageReceived(SearchGuardSSLRequestHandler.java:92) ~[?:?]
        at com.floragunn.searchguard.SearchGuardPlugin$6$1.messageReceived(SearchGuardPlugin.java:525) ~[?:?]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:652) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:637) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.1.0.jar:6.1.0]
        ... 3 more
`

**Comment by antoineco** [comment]
@lucasmello I believe the Elastic community would be a better place to ask non-Docker related questions. Also, it's important to be aware that the elasticsearch documentation has an upgrade path that you have to follow in order to migrate data from a major version to another:
https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html

**Comment by lucasmello** [comment]
Sorry, man. But thanks for the help, anyway!

**Comment by antoineco** [comment]
I didn't have time to look into it yet, but feel free to share your solution when you find one :)
