### ISSUE TITLE
I have a error when start logstash

### ISSUE THREAD

**Issue by dongdx** [deviantony/docker-elk#251]
```
 [2018-03-06T15:40:26,388][ERROR][logstash.pipeline        ] A plugin had an unrecoverable error. Will restart this plugin.
logstash_1       |   Pipeline_id:main
logstash_1       |   Plugin: <LogStash::Inputs::Beats port=>5000, codec=><LogStash::Codecs::JSON id=>"json_56655761-c454-4181-9e93-46881c110fed", enable_metric=>true, charset=>"UTF-8">, id=>"fea2d83a0113df98eaaa5233eb95079d4a224164b376873253f64897ac1d135d", enable_metric=>true, host=>"0.0.0.0", ssl=>false, ssl_verify_mode=>"none", include_codec_tag=>true, ssl_handshake_timeout=>10000, tls_min_version=>1, tls_max_version=>1.2, cipher_suites=>["TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384", "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384", "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256", "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"], client_inactivity_timeout=>60, executor_threads=>96>
logstash_1       |   Error: Address already in use
logstash_1       |   Exception: Java::JavaNet::BindException
logstash_1       |   Stack: sun.nio.ch.Net.bind0(Native Method)
logstash_1       | sun.nio.ch.Net.bind(sun/nio/ch/Net.java:433)
logstash_1       | sun.nio.ch.Net.bind(sun/nio/ch/Net.java:425)
logstash_1       | sun.nio.ch.ServerSocketChannelImpl.bind(sun/nio/ch/ServerSocketChannelImpl.java:223)
logstash_1       | sun.nio.ch.ServerSocketAdaptor.bind(sun/nio/ch/ServerSocketAdaptor.java:74)
logstash_1       | io.netty.channel.socket.nio.NioServerSocketChannel.doBind(io/netty/channel/socket/nio/NioServerSocketChannel.java:125)
logstash_1       | io.netty.channel.AbstractChannel$AbstractUnsafe.bind(io/netty/channel/AbstractChannel.java:554)
logstash_1       | io.netty.channel.DefaultChannelPipeline$HeadContext.bind(io/netty/channel/DefaultChannelPipeline.java:1258)
logstash_1       | io.netty.channel.AbstractChannelHandlerContext.invokeBind(io/netty/channel/AbstractChannelHandlerContext.java:511)
logstash_1       | io.netty.channel.AbstractChannelHandlerContext.bind(io/netty/channel/AbstractChannelHandlerContext.java:496)
logstash_1       | io.netty.channel.DefaultChannelPipeline.bind(io/netty/channel/DefaultChannelPipeline.java:980)
logstash_1       | io.netty.channel.AbstractChannel.bind(io/netty/channel/AbstractChannel.java:250)
logstash_1       | io.netty.bootstrap.AbstractBootstrap$2.run(io/netty/bootstrap/AbstractBootstrap.java:363)
logstash_1       | io.netty.util.concurrent.SingleThreadEventExecutor.safeExecute(io/netty/util/concurrent/SingleThreadEventExecutor.java:451)
logstash_1       | io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(io/netty/util/concurrent/SingleThreadEventExecutor.java:418)
logstash_1       | io.netty.channel.nio.NioEventLoop.run(io/netty/channel/nio/NioEventLoop.java:401)
logstash_1       | io.netty.util.concurrent.SingleThreadEventExecutor$5.run(io/netty/util/concurrent/SingleThreadEventExecutor.java:877)
logstash_1       | io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(io/netty/util/concurrent/DefaultThreadFactory.java:144)
logstash_1       | java.lang.Thread.run(java/lang/Thread.java:748)

logstash_1       | [2018-03-06T15:40:27,397][INFO ][org.logstash.beats.Server] Starting server on port: 5000
logstash_1       | [2018-03-06T15:40:27,401][WARN ][io.netty.channel.AbstractChannel] Force-closing a channel whose registration task was not accepted by an event loop: [id: 0xc69c2679]
logstash_1       | java.util.concurrent.RejectedExecutionException: event executor terminated
logstash_1       |      at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:840) ~[logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:342) ~[logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:335) ~[logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:765) ~[logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:475) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:85) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:330) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:281) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:277) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:259) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at org.logstash.beats.Server.listen(Server.java:65) [logstash-input-beats-5.0.6.jar:?]
logstash_1       |      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
logstash_1       |      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
logstash_1       |      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
logstash_1       |      at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
logstash_1       |      at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:438) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:302) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:36) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at usr.share.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_input_minus_beats_minus_5_dot_0_dot_6_minus_java.lib.logstash.inputs.beats.RUBY$method$run$0(/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-beats-5.0.6-java/lib/logstash/inputs/beats.rb:199) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at usr.share.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_input_minus_beats_minus_5_dot_0_dot_6_minus_java.lib.logstash.inputs.beats.RUBY$method$run$0$__VARARGS__(/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-beats-5.0.6-java/lib/logstash/inputs/beats.rb) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:77) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:93) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at usr.share.logstash.logstash_minus_core.lib.logstash.pipeline.RUBY$method$inputworker$0(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:516) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at usr.share.logstash.logstash_minus_core.lib.logstash.pipeline.RUBY$block$start_input$1(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:509) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:145) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:71) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.runtime.Block.call(Block.java:124) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.RubyProc.call(RubyProc.java:289) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.RubyProc.call(RubyProc.java:246) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:104) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
logstash_1       | [2018-03-06T15:40:27,426][ERROR][io.netty.util.concurrent.DefaultPromise.rejectedExecution] Failed to submit a listener notification task. Event loop shut down?
logstash_1       | java.util.concurrent.RejectedExecutionException: event executor terminated
logstash_1       |      at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:840) ~[logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:342) ~[logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:335) ~[logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:765) ~[logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:767) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:435) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:111) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1062) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:486) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:85) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:330) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:281) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:277) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:259) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at org.logstash.beats.Server.listen(Server.java:65) [logstash-input-beats-5.0.6.jar:?]
logstash_1       |      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
logstash_1       |      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
logstash_1       |      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
logstash_1       |      at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
logstash_1       |      at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:438) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:302) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:36) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at usr.share.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_input_minus_beats_minus_5_dot_0_dot_6_minus_java.lib.logstash.inputs.beats.RUBY$method$run$0(/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-beats-5.0.6-java/lib/logstash/inputs/beats.rb:199) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at usr.share.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_input_minus_beats_minus_5_dot_0_dot_6_minus_java.lib.logstash.inputs.beats.RUBY$method$run$0$__VARARGS__(/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-beats-5.0.6-java/lib/logstash/inputs/beats.rb) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:77) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:93) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at usr.share.logstash.logstash_minus_core.lib.logstash.pipeline.RUBY$method$inputworker$0(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:516) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at usr.share.logstash.logstash_minus_core.lib.logstash.pipeline.RUBY$block$start_input$1(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:509) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:145) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:71) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.runtime.Block.call(Block.java:124) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.RubyProc.call(RubyProc.java:289) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.RubyProc.call(RubyProc.java:246) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:104) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
logstash_1       | [2018-03-06T15:40:27,427][ERROR][io.netty.util.concurrent.DefaultPromise.rejectedExecution] Failed to submit a listener notification task. Event loop shut down?
logstash_1       | java.util.concurrent.RejectedExecutionException: event executor terminated
logstash_1       |      at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:840) ~[logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:342) ~[logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:335) ~[logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:765) ~[logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:767) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:435) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:129) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:906) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:487) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:85) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:330) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:281) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:277) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:259) [logstash-input-tcp-5.0.3.jar:?]
logstash_1       |      at org.logstash.beats.Server.listen(Server.java:65) [logstash-input-beats-5.0.6.jar:?]
logstash_1       |      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
logstash_1       |      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
logstash_1       |      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
logstash_1       |      at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
logstash_1       |      at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:438) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:302) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:36) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at usr.share.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_input_minus_beats_minus_5_dot_0_dot_6_minus_java.lib.logstash.inputs.beats.RUBY$method$run$0(/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-beats-5.0.6-java/lib/logstash/inputs/beats.rb:199) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at usr.share.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_input_minus_beats_minus_5_dot_0_dot_6_minus_java.lib.logstash.inputs.beats.RUBY$method$run$0$__VARARGS__(/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-beats-5.0.6-java/lib/logstash/inputs/beats.rb) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:77) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:93) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at usr.share.logstash.logstash_minus_core.lib.logstash.pipeline.RUBY$method$inputworker$0(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:516) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at usr.share.logstash.logstash_minus_core.lib.logstash.pipeline.RUBY$block$start_input$1(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:509) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:145) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:71) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.runtime.Block.call(Block.java:124) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.RubyProc.call(RubyProc.java:289) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.RubyProc.call(RubyProc.java:246) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:104) [jruby-complete-9.1.13.0.jar:?]
logstash_1       |      at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

**Comment by antoineco** [comment]
`Error: Address already in use`: the interface:port you're trying to bind to is already in use. Make sure you don't have another Logstash instance running.

**Comment by antoineco** [comment]
@dongdx is this issue resolved? If yes, feel free to close this issue 🙌

**Comment by nioerd** [comment]
@antoineco I have the same problem and can't figure out where it comes from.

The "docker-compose.yml" sets 5000:5000 for logstash as port.
So the "logstash.conf" binds port 5000 as an input.

If i stick with the  default configuration (input port 5000), i get the same problem.
The log says the following:
logstash_1       | [2018-03-28T23:32:39,689][INFO ][logstash.inputs.tcp      ] Starting tcp input listener {:address=>"0.0.0.0:5000", :ssl_enable=>"false"}
logstash_1       | [2018-03-28T23:32:39,935][INFO ][logstash.inputs.tcp      ] Starting tcp input listener {:address=>"0.0.0.0:5000", :ssl_enable=>"false"}

Logstash tries to bind two times to port 5000, but why?

I'm not quite sure, if it happens within the first start of the container, but after some shutdowns Ctrl+C, the error appears.
A short grep for "logstash" gives the following results:

ps -ax | grep logstash
 1615 ttys001    0:00.00 grep logstash
  973 ttys005    0:00.08 nvim logstash.yml
 1527 ttys006    0:00.43 nvim logstash.conf

And "docker ps" results:
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

For me it does not seem to be an other instance of logstash.
If i add another port to the docker-compose.yml - lets say 7800:7800 and then change the input port to 7800 i get the following result:

logstash_1       | [2018-03-28T23:41:44,735][INFO ][logstash.inputs.tcp      ] Starting tcp input listener {:address=>"0.0.0.0:7800", :ssl_enable=>"false"}
logstash_1       | [2018-03-28T23:41:44,967][INFO ][logstash.inputs.tcp      ] Starting tcp input listener {:address=>"0.0.0.0:5000", :ssl_enable=>"false"}

CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                                                NAMES
654cf115f861        dockerelk_logstash        "/usr/local/bin/dock…"   2 minutes ago       Up 2 minutes        0.0.0.0:5000->5000/tcp, 5044/tcp, 0.0.0.0:7800->7800/tcp, 9600/tcp   dockerelk_logstash_1
c70a9f4fd260        dockerelk_kibana          "/bin/bash /usr/loca…"   About an hour ago   Up 2 minutes        0.0.0.0:5601->5601/tcp                                               dockerelk_kibana_1
5d2da64fb0de        dockerelk_elasticsearch   "/usr/local/bin/dock…"   About an hour ago   Up 2 minutes        0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp                       dockerelk_elasticsearch_1

It still binds ports 2 times. My logstash.conf has only one tcp element with port => 7800

Any ideas where this could come from?

**Comment by antoineco** [comment]
You must have a duplicate in some file under `logstash/pipeline/`. Did you touch your Dockerfile in any way?
