### ISSUE TITLE
Permission denied in logstash pipeline

### ISSUE THREAD

**Issue by pkaramol** [deviantony/docker-elk#255]
I am creating custom configuration for logstash and in `docker-compose` I am using:

```
logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstash/data:/usr/share/logstash/data
```

In `logstash/pipeline` I am placing two files, i.e. one `main.conf` and a `filter.conf`.

In the first one:

```
input {

  file {
    path => "/usr/share/logstash/data/a_huge_logfile.log"
    start_position => "beginning"
  }

}
```

When logstash service starts:

```
logstash_1       | [2018-03-21T17:06:38,391][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<Errno::EACCES: Permission denied - /logstash_data>, :backtrace=>["org/jruby/RubyDir.java:449:in `mkdir'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/fileutils.rb:253:in `fu_mkdir'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/fileutils.rb:227:in `block in mkdir_p'", "org/jruby/RubyArray.java:1818:in `reverse_each'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/fileutils.rb:225:in `block in mkdir_p'", "org/jruby/RubyArray.java:1734:in `each'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/fileutils.rb:211:in `mkdir_p'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-file-4.2.1/lib/logstash/outputs/file.rb:278:in `open'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-file-4.2.1/lib/logstash/outputs/file.rb:135:in `block in multi_receive_encoded'", "org/jruby/RubyHash.java:1343:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-file-4.2.1/lib/logstash/outputs/file.rb:134:in `block in multi_receive_encoded'", "org/jruby/ext/thread/Mutex.java:148:in `synchronize'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-file-4.2.1/lib/logstash/outputs/file.rb:133:in `multi_receive_encoded'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:90:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:13:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:49:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:479:in `block in output_batch'", "org/jruby/RubyHash.java:1343:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:478:in `output_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:430:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:385:in `block in start_workers'"]}
```
From within the specific container:

```
bash-4.2$ ls -ald /usr/share/logstash/data/
drwxrwxr-x 5 logstash logstash 4096 Mar 21 16:44 /usr/share/logstash/data/
```

Where does the permission error come from?

**Comment by pkaramol** [comment]
Hi thx for the feedback;

The combination of 1) and 2) gave me this:


```
logstash_1       | [2018-03-22T08:20:43,161][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ArgumentError: Path "/usr/share/logstash/data/queue" must be a writable directory. It is not writable.>, :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/settings.rb:448:in `validate'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:230:in `validate_value'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:141:in `block in validate_all'", "org/jruby/RubyHash.java:1343:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:140:in `validate_all'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:264:in `execute'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:219:in `run'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/usr/share/logstash/lib/bootstrap/environment.rb:67:in `<main>'"]}
logstash_1       | [2018-03-22T08:20:43,182][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: org.jruby.exceptions.RaiseException: (SystemExit) exit
```

I tried to `chmod` back to `1000:1000` and `777` everything and still getting the initial error..

**Comment by antoineco** [comment]
`chmod 777` is generally a bad idea, but `chown 1000` is indeed mandatory on Linux.

What surprises me is this error message: `Permission denied - /logstash_data`. I don't see this directory in your configuration, yet it's causing trouble.

**Comment by pkaramol** [comment]
From within the `logstash` container:


```
bash-4.2$ sudo ls
bash: sudo: command not found
bash-4.2$ find / -iname "*logstash_data*"
find: ‘/var/cache/ldconfig’: Permission denied
find: ‘/var/lib/yum/history/2018-01-07/4’: Permission denied
find: ‘/var/lib/yum/history/2018-01-07/3’: Permission denied
find: ‘/var/lib/yum/history/2018-01-07/1’: Permission denied
find: ‘/var/lib/yum/history/2018-01-07/2’: Permission denied
find: ‘/var/lib/machines’: Permission denied
find: ‘/root’: Permission denied
find: ‘/proc/tty/driver’: Permission denied
```

**Comment by antoineco** [comment]
That's expected and perfectly fine since logstash doesn't run as root. I don't see any logstash related directory here.

**Comment by antoineco** [comment]
Aha, interesting, looks like it's trying to create that directory:
`org/jruby/RubyDir.java:449:in `mkdir'"`

**Comment by antoineco** [comment]
Looks to me like you started with some sample config (this? https://gist.github.com/nicolaihald/5dd066aa29b312252c7485c32f4b0b77) and forgot to clean the reference to that particular directory in one of your pipeline files?

**Comment by pkaramol** [comment]
Yes I am using `/logstash_data` in my output pipeline, it just came to me.
I am switching it to `/data` which gets created on the container either way and is owned by `logstash` user.
many thanks.

**Comment by pkaramol** [comment]
Just for the record, my pipeline is (supposed to be) and I have extremely simplified things using:

a) `0_1_input.conf`

```
input {

  file {
    path => "/usr/share/logstash/data/some_log_file.log"
  }
}
```

b) `0_2_output.conf`

```
output {
    stdout {
      codec => json_lines
    }
  }
```

However the combined `docker-compose` logs are stuck forever at this point:

```
logstash_1       | Sending Logstash's logs to /usr/share/logstash/logs which is now configured via log4j2.properties
logstash_1       | [2018-03-22T10:40:12,781][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"netflow", :directory=>"/usr/share/logstash/modules/netflow/configuration"}
logstash_1       | [2018-03-22T10:40:12,810][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"fb_apache", :directory=>"/usr/share/logstash/modules/fb_apache/configuration"}
logstash_1       | [2018-03-22T10:40:13,745][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
logstash_1       | [2018-03-22T10:40:15,091][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.2.2"}
logstash_1       | [2018-03-22T10:40:15,852][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
logstash_1       | [2018-03-22T10:40:19,128][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>4, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50}
logstash_1       | [2018-03-22T10:40:19,968][INFO ][logstash.pipeline        ] Pipeline started succesfully {:pipeline_id=>"main", :thread=>"#<Thread:0x58cb91de run>"}
logstash_1       | [2018-03-22T10:40:20,272][INFO ][logstash.agent           ] Pipelines running {:count=>1, :pipelines=>["main"]}
```


The input file does exist: (following is from within the container:

```
bash-4.2$ ls -al /usr/share/logstash/data/some_log_file.log
-rwxrwxrwx 1 logstash logstash 727460 Mar 22 09:17 //usr/share/logstash/data/some_log_file.log
```

**Comment by antoineco** [comment]
Looks good to me. Don't you see any data in Elasticsearch?

**Comment by pkaramol** [comment]
Kibana says: 

> Couldn't find any Elasticsearch data

Either way I am not sending them explicitly to ES;

The question is why the above simple configuration does not just simply print the contents of 

`path => "/usr/share/logstash/data/some_log_file.log"`

to `stdout`.

**Comment by antoineco** [comment]
Looks good to me. Don't you see any data in Elasticsearch?

**Comment by antoineco** [comment]
@pkaramol unfortunately I have no idea about the stdout output. Did you ask in the Elastic discussion forums?

Regardless, since the initial problem is now solved I'm gonna go ahead and close this.

You can still comment below of course.
