### ISSUE TITLE
OOM errors on s3 output plugin

### ISSUE THREAD

**Issue by psankar** [deviantony/docker-elk#328]
### Problem description

As soon as we start the docker compose services with the s3 output plugin, we get an out-of-memory exception.

#### Stack configuration

I am using vanilla docker-elk sources HEAD, with just the logstash.conf file changed as follows: 

```
input {
	beats {
		port => 5000
			codec => plain {
				charset => "UTF-8"
			}
	}
}

filter {
}

output {
	elasticsearch {
		hosts => "elasticsearch:9200"
	}
	s3 {
		access_key_id => ""
		secret_access_key => ""
		region => "us-east-1"
		bucket => ""
		size_file => 2048
		time_file => 5
		codec => "plain"
		canned_acl => "private"
	}
}
```
If the s3 output is disabled, the programs run smooth.

#### Docker setup

```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   a04f55b
 Built:        Thu Sep 21 20:36:57 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   a04f55b
 Built:        Thu Sep 21 20:36:57 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

#### Docker logs
```
logstash_1       | java.lang.OutOfMemoryError: Java heap space
logstash_1       | Dumping heap to java_pid1.hprof ...
logstash_1       | Heap dump file created [400344941 bytes in 2.922 secs]
logstash_1       | [2018-10-07T15:07:33,147][INFO ][org.logstash.beats.BeatsHandler] [local: 172.18.0.3:5000, remote: 104.211.102.193:49728] Handling exception: Java heap space
logstash_1       | [2018-10-07T15:07:33,149][WARN ][io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
logstash_1       | java.lang.OutOfMemoryError: Java heap space
logstash_1       | 	at io.netty.util.internal.PlatformDependent.allocateUninitializedArray(PlatformDependent.java:200) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
logstash_1       | 	at io.netty.buffer.PoolArena$HeapArena.newByteArray(PoolArena.java:676) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
logstash_1       | 	at io.netty.buffer.PoolArena$HeapArena.newChunk(PoolArena.java:686) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
logstash_1       | 	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
logstash_1       | 	at io.netty.buffer.PoolArena.allocate(PoolArena.java:226) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
logstash_1       | 	at io.netty.buffer.PoolArena.allocate(PoolArena.java:146) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
logstash_1       | 	at io.netty.buffer.PooledByteBufAllocator.newHeapBuffer(PooledByteBufAllocator.java:307) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
logstash_1       | 	at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:166) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
logstash_1       | 	at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:157) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
logstash_1       | 	at io.netty.buffer.UnsafeByteBufUtil.getBytes(UnsafeByteBufUtil.java:572) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
logstash_1       | 	at io.netty.buffer.PooledUnsafeDirectByteBuf.getBytes(PooledUnsafeDirectByteBuf.java:152) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
logstash_1       | 	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:939) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
logstash_1       | 	at org.logstash.beats.BeatsParser.decode(BeatsParser.java:181) ~[logstash-input-beats-5.1.6.jar:?]
logstash_1       | 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
logstash_1       | 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
logstash_1       | 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
logstash_1       | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
logstash_1       | 	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
logstash_1       | 	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:353) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
logstash_1       | 	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
logstash_1       | 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.18.Final.jar:4.1.18.Final]
logstash_1       | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.18.Final.jar:4.1.18.Final]
logstash_1       | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by antoineco** [comment]
You need to increase the heap size of Logstash. Please refer to the [instructions in the README](https://github.com/deviantony/docker-elk/blob/master/README.md#how-can-i-specify-the-amount-of-memory-used-by-a-service).

**Comment by psankar** [comment]
Thanks. Closing this as a non-issue. I am still not able to see the files in the S3 bucket but that I believe that could be a different issue, which I would debug and try to fix, without keeping this issue open. Thanks a lot for your help @antoineco 👍
