### ISSUE TITLE
kibana exists with error on the searchguard branch

### ISSUE THREAD

**Issue by ami-m** [deviantony/docker-elk#347]
Hi,

### Problem description

I built the containers and raised the environment according to the instructions, but the kibana container exits with code 1

I'm on the searchguard branch, commit ec1dbc70b70ac2ee3be70d9 (Upgrade to Version 6.5.2 )
All I did was clone the repo, co the branch, docker-compose up and ran the init_sg.sh script.

#### Docker setup

```
 docker version
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```

```
docker-compose version
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

```

#### Docker logs

```
kibana_1         | {"type":"error","@timestamp":"2018-12-25T15:19:23Z","tags":["fatal","root"],"pid":1,"level":"fatal","error":{"message":"[security_exception] no permissions for [indices:admin/create] and User [name=kibanaserver, roles=[], requestedTenant=null]","name":"Error","stack":"[security_exception] no permissions for [indices:admin/create] and User [name=kibanaserver, roles=[], requestedTenant=null] :: {\"path\":\"/.kibana_1\",\"query\":{},\"body\":\"{\\\"mappings\\\":{\\\"doc\\\":{\\\"dynamic\\\":\\\"strict\\\",\\\"properties\\\":{\\\"config\\\":{\\\"dynamic\\\":\\\"true\\\",\\\"properties\\\":{\\\"buildNum\\\":{\\\"type\\\":\\\"keyword\\\"}}},\\\"migrationVersion\\\":{\\\"dynamic\\\":\\\"true\\\",\\\"type\\\":\\\"object\\\"},\\\"type\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"namespace\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"updated_at\\\":{\\\"type\\\":\\\"date\\\"},\\\"timelion-sheet\\\":{\\\"properties\\\":{\\\"description\\\":{\\\"type\\\":\\\"text\\\"},\\\"hits\\\":{\\\"type\\\":\\\"integer\\\"},\\\"kibanaSavedObjectMeta\\\":{\\\"properties\\\":{\\\"searchSourceJSON\\\":{\\\"type\\\":\\\"text\\\"}}},\\\"timelion_chart_height\\\":{\\\"type\\\":\\\"integer\\\"},\\\"timelion_columns\\\":{\\\"type\\\":\\\"integer\\\"},\\\"timelion_interval\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"timelion_other_interval\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"timelion_rows\\\":{\\\"type\\\":\\\"integer\\\"},\\\"timelion_sheet\\\":{\\\"type\\\":\\\"text\\\"},\\\"title\\\":{\\\"type\\\":\\\"text\\\"},\\\"version\\\":{\\\"type\\\":\\\"integer\\\"}}},\\\"index-pattern\\\":{\\\"properties\\\":{\\\"fieldFormatMap\\\":{\\\"type\\\":\\\"text\\\"},\\\"fields\\\":{\\\"type\\\":\\\"text\\\"},\\\"intervalName\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"notExpandable\\\":{\\\"type\\\":\\\"boolean\\\"},\\\"sourceFilters\\\":{\\\"type\\\":\\\"text\\\"},\\\"timeFieldName\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"title\\\":{\\\"type\\\":\\\"text\\\"},\\\"type\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"typeMeta\\\":{\\\"type\\\":\\\"keyword\\\"}}},\\\"visualization\\\":{\\\"properties\\\":{\\\"description\\\":{\\\"type\\\":\\\"text\\\"},\\\"kibanaSavedObjectMeta\\\":{\\\"properties\\\":{\\\"searchSourceJSON\\\":{\\\"type\\\":\\\"text\\\"}}},\\\"savedSearchId\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"title\\\":{\\\"type\\\":\\\"text\\\"},\\\"uiStateJSON\\\":{\\\"type\\\":\\\"text\\\"},\\\"version\\\":{\\\"type\\\":\\\"integer\\\"},\\\"visState\\\":{\\\"type\\\":\\\"text\\\"}}},\\\"search\\\":{\\\"properties\\\":{\\\"columns\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"description\\\":{\\\"type\\\":\\\"text\\\"},\\\"hits\\\":{\\\"type\\\":\\\"integer\\\"},\\\"kibanaSavedObjectMeta\\\":{\\\"properties\\\":{\\\"searchSourceJSON\\\":{\\\"type\\\":\\\"text\\\"}}},\\\"sort\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"title\\\":{\\\"type\\\":\\\"text\\\"},\\\"version\\\":{\\\"type\\\":\\\"integer\\\"}}},\\\"dashboard\\\":{\\\"properties\\\":{\\\"description\\\":{\\\"type\\\":\\\"text\\\"},\\\"hits\\\":{\\\"type\\\":\\\"integer\\\"},\\\"kibanaSavedObjectMeta\\\":{\\\"properties\\\":{\\\"searchSourceJSON\\\":{\\\"type\\\":\\\"text\\\"}}},\\\"optionsJSON\\\":{\\\"type\\\":\\\"text\\\"},\\\"panelsJSON\\\":{\\\"type\\\":\\\"text\\\"},\\\"refreshInterval\\\":{\\\"properties\\\":{\\\"display\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"pause\\\":{\\\"type\\\":\\\"boolean\\\"},\\\"section\\\":{\\\"type\\\":\\\"integer\\\"},\\\"value\\\":{\\\"type\\\":\\\"integer\\\"}}},\\\"timeFrom\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"timeRestore\\\":{\\\"type\\\":\\\"boolean\\\"},\\\"timeTo\\\":{\\\"type\\\":\\\"keyword\\\"},\\\"title\\\":{\\\"type\\\":\\\"text\\\"},\\\"uiStateJSON\\\":{\\\"type\\\":\\\"text\\\"},\\\"version\\\":{\\\"type\\\":\\\"integer\\\"}}},\\\"url\\\":{\\\"properties\\\":{\\\"accessCount\\\":{\\\"type\\\":\\\"long\\\"},\\\"accessDate\\\":{\\\"type\\\":\\\"date\\\"},\\\"createDate\\\":{\\\"type\\\":\\\"date\\\"},\\\"url\\\":{\\\"type\\\":\\\"text\\\",\\\"fields\\\":{\\\"keyword\\\":{\\\"type\\\":\\\"keyword\\\",\\\"ignore_above\\\":2048}}}}},\\\"server\\\":{\\\"properties\\\":{\\\"uuid\\\":{\\\"type\\\":\\\"keyword\\\"}}},\\\"kql-telemetry\\\":{\\\"properties\\\":{\\\"optInCount\\\":{\\\"type\\\":\\\"long\\\"},\\\"optOutCount\\\":{\\\"type\\\":\\\"long\\\"}}}}}},\\\"settings\\\":{\\\"number_of_shards\\\":1,\\\"auto_expand_replicas\\\":\\\"0-1\\\"}}\",\"statusCode\":403,\"response\":\"{\\\"error\\\":{\\\"root_cause\\\":[{\\\"type\\\":\\\"security_exception\\\",\\\"reason\\\":\\\"no permissions for [indices:admin/create] and User [name=kibanaserver, roles=[], requestedTenant=null]\\\"}],\\\"type\\\":\\\"security_exception\\\",\\\"reason\\\":\\\"no permissions for [indices:admin/create] and User [name=kibanaserver, roles=[], requestedTenant=null]\\\"},\\\"status\\\":403}\"}\n    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:308:15)\n    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:267:7)\n    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:165:7)\n    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/lodash.js:4949:19)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\n    at process._tickCallback (internal/process/next_tick.js:181:9)"},"message":"[security_exception] no permissions for [indices:admin/create] and User [name=kibanaserver, roles=[], requestedTenant=null]"}
kibana_1         | 
kibana_1         |  FATAL  [security_exception] no permissions for [indices:admin/create] and User [name=kibanaserver, roles=[], requestedTenant=null] :: {"path":"/.kibana_1","query":{},"body":"{\"mappings\":{\"doc\":{\"dynamic\":\"strict\",\"properties\":{\"config\":{\"dynamic\":\"true\",\"properties\":{\"buildNum\":{\"type\":\"keyword\"}}},\"migrationVersion\":{\"dynamic\":\"true\",\"type\":\"object\"},\"type\":{\"type\":\"keyword\"},\"namespace\":{\"type\":\"keyword\"},\"updated_at\":{\"type\":\"date\"},\"timelion-sheet\":{\"properties\":{\"description\":{\"type\":\"text\"},\"hits\":{\"type\":\"integer\"},\"kibanaSavedObjectMeta\":{\"properties\":{\"searchSourceJSON\":{\"type\":\"text\"}}},\"timelion_chart_height\":{\"type\":\"integer\"},\"timelion_columns\":{\"type\":\"integer\"},\"timelion_interval\":{\"type\":\"keyword\"},\"timelion_other_interval\":{\"type\":\"keyword\"},\"timelion_rows\":{\"type\":\"integer\"},\"timelion_sheet\":{\"type\":\"text\"},\"title\":{\"type\":\"text\"},\"version\":{\"type\":\"integer\"}}},\"index-pattern\":{\"properties\":{\"fieldFormatMap\":{\"type\":\"text\"},\"fields\":{\"type\":\"text\"},\"intervalName\":{\"type\":\"keyword\"},\"notExpandable\":{\"type\":\"boolean\"},\"sourceFilters\":{\"type\":\"text\"},\"timeFieldName\":{\"type\":\"keyword\"},\"title\":{\"type\":\"text\"},\"type\":{\"type\":\"keyword\"},\"typeMeta\":{\"type\":\"keyword\"}}},\"visualization\":{\"properties\":{\"description\":{\"type\":\"text\"},\"kibanaSavedObjectMeta\":{\"properties\":{\"searchSourceJSON\":{\"type\":\"text\"}}},\"savedSearchId\":{\"type\":\"keyword\"},\"title\":{\"type\":\"text\"},\"uiStateJSON\":{\"type\":\"text\"},\"version\":{\"type\":\"integer\"},\"visState\":{\"type\":\"text\"}}},\"search\":{\"properties\":{\"columns\":{\"type\":\"keyword\"},\"description\":{\"type\":\"text\"},\"hits\":{\"type\":\"integer\"},\"kibanaSavedObjectMeta\":{\"properties\":{\"searchSourceJSON\":{\"type\":\"text\"}}},\"sort\":{\"type\":\"keyword\"},\"title\":{\"type\":\"text\"},\"version\":{\"type\":\"integer\"}}},\"dashboard\":{\"properties\":{\"description\":{\"type\":\"text\"},\"hits\":{\"type\":\"integer\"},\"kibanaSavedObjectMeta\":{\"properties\":{\"searchSourceJSON\":{\"type\":\"text\"}}},\"optionsJSON\":{\"type\":\"text\"},\"panelsJSON\":{\"type\":\"text\"},\"refreshInterval\":{\"properties\":{\"display\":{\"type\":\"keyword\"},\"pause\":{\"type\":\"boolean\"},\"section\":{\"type\":\"integer\"},\"value\":{\"type\":\"integer\"}}},\"timeFrom\":{\"type\":\"keyword\"},\"timeRestore\":{\"type\":\"boolean\"},\"timeTo\":{\"type\":\"keyword\"},\"title\":{\"type\":\"text\"},\"uiStateJSON\":{\"type\":\"text\"},\"version\":{\"type\":\"integer\"}}},\"url\":{\"properties\":{\"accessCount\":{\"type\":\"long\"},\"accessDate\":{\"type\":\"date\"},\"createDate\":{\"type\":\"date\"},\"url\":{\"type\":\"text\",\"fields\":{\"keyword\":{\"type\":\"keyword\",\"ignore_above\":2048}}}}},\"server\":{\"properties\":{\"uuid\":{\"type\":\"keyword\"}}},\"kql-telemetry\":{\"properties\":{\"optInCount\":{\"type\":\"long\"},\"optOutCount\":{\"type\":\"long\"}}}}}},\"settings\":{\"number_of_shards\":1,\"auto_expand_replicas\":\"0-1\"}}","statusCode":403,"response":"{\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"no permissions for [indices:admin/create] and User [name=kibanaserver, roles=[], requestedTenant=null]\"}],\"type\":\"security_exception\",\"reason\":\"no permissions for [indices:admin/create] and User [name=kibanaserver, roles=[], requestedTenant=null]\"},\"status\":403}"}
kibana_1         | 
kibana3_kibana_1 exited with code 1

```

**Comment by antoineco** [comment]
Could you run `docker-compose build` and try again?

**Comment by ami-m** [comment]
I tried to rebuild (with and without cache), but I get the same results.
always after I run the init_sg.sh script.

I'm not familiar with search guard, but it seems like tweaking the permission definitions should do it, no?
(I'll try and post my results here)

thanks!

**Comment by valh1996** [comment]
I confirm that I have the same concern. Even if i run `docker-compose build`

**Comment by antoineco** [comment]
I'm being quite unsuccessful trying to reproduce this issue unfortunately. I'd recommend you to check your permissions:
* is any security layer preventing Docker from reading your local files? (SELinux, AppArmor, ...)
* are your local config files readable by the uid 1000? (see README)

**Environment**

```console
$ docker-compose version
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```
```console
docker version
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Procedure**

Bring up the stack:
```console
$ docker-compose up -d
Creating network "docker-elk_elk" with driver "bridge"
Building elasticsearch
[...]
Successfully built 59c817b90783
Successfully tagged docker-elk_elasticsearch:latest
Building logstash
[...]
Successfully built d08cbc42c2fe
Successfully tagged docker-elk_logstash:latest
Building kibana
[...]
Successfully built xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Successfully tagged docker-elk_kibana:latest
```

All Search Guard config files are mounted inside the Elasticsearch container:
```console
$ docker-compose exec elasticsearch ls -l config/sg/
total 40
-rw------- 1 elasticsearch root 4422 Dec 13 21:44 kirk-keystore.jks
-rw------- 1 elasticsearch root 4491 Dec 13 21:44 node-0-keystore.jks
-rw------- 1 elasticsearch root 2365 Dec 13 21:44 sg_action_groups.yml
-rw------- 1 elasticsearch root  218 Dec 13 21:44 sg_config.yml
-rw------- 1 elasticsearch root  923 Dec 13 21:44 sg_internal_users.yml
-rw------- 1 elasticsearch root 2095 Dec 13 21:44 sg_roles.yml
-rw------- 1 elasticsearch root  541 Dec 13 21:44 sg_roles_mapping.yml
-rw------- 1 elasticsearch root 1096 Dec 13 21:44 truststore.jks
```

Initializing Searchguard succeeds:
```console
$ docker-compose exec -T elasticsearch bin/init_sg.sh
Search Guard Admin v6
Will connect to localhost:9300 ... done
Elasticsearch Version: 6.5.2
Search Guard Version: 6.5.2-23.2
Connected as CN=kirk,OU=client,O=client,L=Test,C=DE
Contacting elasticsearch cluster 'elasticsearch' and wait for YELLOW clusterstate ...
Clustername: docker-cluster
Clusterstate: GREEN
Number of nodes: 1
Number of data nodes: 1
searchguard index does not exists, attempt to create it ... done (0-all replicas)
Populate config from /usr/share/elasticsearch/config/sg
Will update 'sg/config' with config/sg/sg_config.yml 
   SUCC: Configuration for 'config' created or updated
Will update 'sg/roles' with config/sg/sg_roles.yml 
   SUCC: Configuration for 'roles' created or updated
Will update 'sg/rolesmapping' with config/sg/sg_roles_mapping.yml 
   SUCC: Configuration for 'rolesmapping' created or updated
Will update 'sg/internalusers' with config/sg/sg_internal_users.yml 
   SUCC: Configuration for 'internalusers' created or updated
Will update 'sg/actiongroups' with config/sg/sg_action_groups.yml 
   SUCC: Configuration for 'actiongroups' created or updated
Done with success
```

**Comment by antoineco** [comment]
@ami-m My bad, I got distracted by your third comment and lost track of the real problem: Kibana.

I'm pushing a fix to the repo, thanks for reporting!
