### ISSUE TITLE
Start x-pack branch

### ISSUE THREAD

**Issue by fabioebner** [deviantony/docker-elk#355]
When I try to run docker-compose up in x-pack branch I got the error:

```

[2019-01-25T16:35:04,329][INFO ][o.e.p.PluginsService     ] [1TRKhHS] loaded module [aggs-matrix-stats]
elasticsearch_1  | [2019-01-25T16:35:04,330][INFO ][o.e.p.PluginsService     ] [1TRKhHS] loaded module [analysis-common]
elasticsearch_1  | [2019-01-25T16:35:04,330][INFO ][o.e.p.PluginsService     ] [1TRKhHS] loaded module [ingest-common]
elasticsearch_1  | [2019-01-25T16:35:04,331][INFO ][o.e.p.PluginsService     ] [1TRKhHS] loaded module [lang-expression]
elasticsearch_1  | [2019-01-25T16:35:04,332][INFO ][o.e.p.PluginsService     ] [1TRKhHS] loaded module [lang-mustache]
elasticsearch_1  | [2019-01-25T16:35:04,332][INFO ][o.e.p.PluginsService     ] [1TRKhHS] loaded module [lang-painless]
elasticsearch_1  | [2019-01-25T16:35:04,333][INFO ][o.e.p.PluginsService     ] [1TRKhHS] loaded module [mapper-extras]
elasticsearch_1  | [2019-01-25T16:35:04,338][INFO ][o.e.p.PluginsService     ] [1TRKhHS] loaded module [parent-join]
elasticsearch_1  | [2019-01-25T16:35:04,338][INFO ][o.e.p.PluginsService     ] [1TRKhHS] loaded module [percolator]
elasticsearch_1  | [2019-01-25T16:35:04,339][INFO ][o.e.p.PluginsService     ] [1TRKhHS] loaded module [rank-eval]
elasticsearch_1  | [2019-01-25T16:35:04,340][INFO ][o.e.p.PluginsService     ] [1TRKhHS] loaded module [reindex]
elasticsearch_1  | [2019-01-25T16:35:04,340][INFO ][o.e.p.PluginsService     ] [1TRKhHS] loaded module [repository-url]
elasticsearch_1  | [2019-01-25T16:35:04,341][INFO ][o.e.p.PluginsService     ] [1TRKhHS] loaded module [transport-netty4]
elasticsearch_1  | [2019-01-25T16:35:04,341][INFO ][o.e.p.PluginsService     ] [1TRKhHS] loaded module [tribe]
elasticsearch_1  | [2019-01-25T16:35:04,343][INFO ][o.e.p.PluginsService     ] [1TRKhHS] loaded plugin [ingest-geoip]
elasticsearch_1  | [2019-01-25T16:35:04,347][INFO ][o.e.p.PluginsService     ] [1TRKhHS] loaded plugin [ingest-user-agent]
elasticsearch_1  | [2019-01-25T16:35:11,845][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [1TRKhHS] uncaught exception in thread [main]
elasticsearch_1  | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [xpack.license.self_generated.type] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:140) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.5.4.jar:6.5.4]
elasticsearch_1  | 	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.5.4.jar:6.5.4]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | Caused by: java.lang.IllegalArgumentException: unknown setting [xpack.license.self_generated.type] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
elasticsearch_1  | 	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:476) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:421) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:392) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:363) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 	at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:148) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:373) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 	... 6 more
elasticsearch_1  | 	Suppressed: java.lang.IllegalArgumentException: unknown setting [xpack.security.enabled] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
elasticsearch_1  | 		at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:476) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 		at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:421) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 		at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:392) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 		at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:363) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 		at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:148) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 		at org.elasticsearch.node.Node.<init>(Node.java:373) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 		at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 		at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 		at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 		at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 		at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 		at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 		at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 		at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.5.4.jar:6.5.4]
elasticsearch_1  | 		at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.5.4.jar:6.5.4]
elasticsearch_1  | 		at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.5.4.jar:6.5.4]
elasticsearch_1  | 		at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) ~[elasticsearch-6.5.4.jar:6.5.4]
docker-elk_elasticsearch_1 exited with code 1
logstash_1       | Sending Logstash logs to /usr/share/logstash/logs which is now configured via log4j2.properties
logstash_1       | [2019-01-25T16:35:39,470][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ArgumentError: Setting "xpack.monitoring.elasticsearch.url" hasn't been registered>, :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/settings.rb:36:in `get_setting'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:69:in `set_value'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:88:in `block in merge'", "org/jruby/RubyHash.java:1343:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:88:in `merge'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:137:in `validate_all'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:278:in `execute'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:237:in `run'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/usr/share/logstash/lib/bootstrap/environment.rb:73:in `<main>'"]}
logstash_1       | [2019-01-25T16:35:39,497][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit
docker-elk_logstash_1 exited with code 1
```

**Comment by antoineco** [comment]
`unknown setting [xpack...]` means X-Pack is not installed. Unfortunately it's impossible for us to help you if you don't fill the issue template because we have no clue what modifications you performed in your repo.

Closing. Please re-open with the requested details about your environment.
