### ISSUE TITLE
Minimal requirements for host machine

### ISSUE THREAD

**Issue by FrameBassman** [deviantony/docker-elk#419]
### Problem description
I have VM with `512 MB RAM` and `1 CPU`
When I run `docker-compose up` - I have 100% CPU loading and the following in logstash logs:
```
java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid1.hprof ...
Heap dump file created [105798879 bytes in 1.156 secs]
[ERROR] 2019-07-24 07:21:05.141 [main] Logstash - java.lang.IllegalStateException: Logstash stopped processing because of an error: (LoadError) load error: logstash/config/grammar -- java.lang.OutOfMemoryError: Java heap space
```
and elasticsearch logs
```
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000faaa0000, 89522176, 0) failed; error='Not enough space' (errno=12)
	at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:111)
	at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:79)
	at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:57)
	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:89)
``` 
I want to notice that there are the following configuration in docker-compose:
```
services:
  elasticsearch:
  ...
    environment:
      ES_JAVA_OPTS: "-Xmx128m -Xms128m"
  ...
  logstash:
  ...
    environment:
      LS_JAVA_OPTS: "-Xmx128m -Xms128m"
  ...
```

Are there any minimal requirements for host machine in this case?
Maybe I should run containers one by one: start from `elasticsearch`, than `logstash` and finally `kibana`?

#### Docker setup

```
root@elastic ~ # docker version
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Wed Jul  3 12:13:59 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       2d0083d
  Built:            Mon Jul  1 19:31:12 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

```
root@elastic ~ # docker-compose version
docker-compose version 1.24.1, build 4667896
docker-py version: 3.7.3
CPython version: 2.7.15+
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
```

#### Docker logs

```
root@elastic ~ # docker logs docker-elk_logstash_1 -f
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.headius.backport9.modules.Modules (file:/usr/share/logstash/logstash-core/lib/jars/jruby-complete-9.2.7.0.jar) to field java.io.FileDescriptor.fd
WARNING: Please consider reporting this to the maintainers of com.headius.backport9.modules.Modules
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid1.hprof ...
Heap dump file created [105798879 bytes in 1.156 secs]
[ERROR] 2019-07-24 07:21:05.141 [main] Logstash - java.lang.IllegalStateException: Logstash stopped processing because of an error: (LoadError) load error: logstash/config/grammar -- java.lang.OutOfMemoryError: Java heap space
```

```
root@elastic ~ # docker logs docker-elk_elasticsearch_1 -f
Created elasticsearch keystore in /usr/share/elasticsearch/config
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
{"type": "server", "timestamp": "2019-07-24T07:09:04,660+0000", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/vda1)]], net usable_space [13.3gb], net total_space [19.6gb], types [ext4]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:04,687+0000", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "heap size [123.7mb], compressed ordinary object pointers [true]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:04,765+0000", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "node name [cb3184021e94], node ID [ZnuwsNZIQ1yATwZP1kUJ5g], cluster name [docker-cluster]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:04,771+0000", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "version[7.2.0], pid[1], build[default/docker/508c38a/2019-06-20T15:54:18.811730Z], OS[Linux/4.15.0-55-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/12.0.1/12.0.1+12]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:04,777+0000", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "JVM home [/usr/share/elasticsearch/jdk]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:04,778+0000", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch-17909871231326196457, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Djava.locale.providers=COMPAT, -Des.cgroups.hierarchy.override=/, -Xmx128m, -Xms128m, -Dio.netty.allocator.type=unpooled, -XX:MaxDirectMemorySize=67108864, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=docker, -Des.bundled_jdk=true]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,735+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [aggs-matrix-stats]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,735+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [analysis-common]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,736+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [data-frame]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,737+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [ingest-common]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,737+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [ingest-geoip]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,738+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [ingest-user-agent]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,739+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [lang-expression]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,740+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [lang-mustache]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,743+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [lang-painless]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,743+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [mapper-extras]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,743+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [parent-join]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,744+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [percolator]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,744+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [rank-eval]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,744+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [reindex]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,745+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [repository-url]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,746+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [transport-netty4]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,750+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [x-pack-ccr]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,750+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [x-pack-core]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,751+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [x-pack-deprecation]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,755+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [x-pack-graph]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,755+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [x-pack-ilm]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,755+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [x-pack-logstash]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,756+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [x-pack-ml]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,757+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [x-pack-monitoring]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,757+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [x-pack-rollup]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,758+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [x-pack-security]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,758+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [x-pack-sql]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,759+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "loaded module [x-pack-watcher]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:32,759+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "no plugins loaded"  }
{"type": "server", "timestamp": "2019-07-24T07:09:44,936+0000", "level": "INFO", "component": "o.e.x.s.a.s.FileRolesStore", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "parsed [0] roles from file [/usr/share/elasticsearch/config/roles.yml]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:47,129+0000", "level": "INFO", "component": "o.e.x.m.p.l.CppLogMessageHandler", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "[controller/213] [Main.cc@110] controller (64 bit): Version 7.2.0 (Build 65aefcbfce449b) Copyright (c) 2019 Elasticsearch BV"  }
{"type": "server", "timestamp": "2019-07-24T07:09:48,166+0000", "level": "DEBUG", "component": "o.e.a.ActionModule", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "Using REST wrapper from plugin org.elasticsearch.xpack.security.Security"  }
{"type": "server", "timestamp": "2019-07-24T07:09:49,129+0000", "level": "INFO", "component": "o.e.d.DiscoveryModule", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "using discovery type [single-node] and seed hosts providers [settings]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:51,343+0000", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "initialized"  }
{"type": "server", "timestamp": "2019-07-24T07:09:51,343+0000", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "starting ..."  }
{"type": "server", "timestamp": "2019-07-24T07:09:51,746+0000", "level": "INFO", "component": "o.e.t.TransportService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "publish_address {172.19.0.2:9300}, bound_addresses {0.0.0.0:9300}"  }
{"type": "server", "timestamp": "2019-07-24T07:09:51,828+0000", "level": "WARN", "component": "o.e.b.BootstrapChecks", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:51,829+0000", "level": "WARN", "component": "o.e.b.BootstrapChecks", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "Transport SSL must be enabled if security is enabled on a [basic] license. Please set [xpack.security.transport.ssl.enabled] to [true] or disable security by setting [xpack.security.enabled] to [false]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:51,841+0000", "level": "INFO", "component": "o.e.c.c.Coordinator", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "cluster UUID [vOjTUfOHQZORLeDRFKbV0w]"  }
{"type": "server", "timestamp": "2019-07-24T07:09:52,334+0000", "level": "INFO", "component": "o.e.c.s.MasterService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "elected-as-master ([1] nodes joined)[{cb3184021e94}{ZnuwsNZIQ1yATwZP1kUJ5g}{aiJTDRlMQDmnDDSIQ0BhSg}{172.19.0.2}{172.19.0.2:9300}{ml.machine_memory=504868864, xpack.installed=true, ml.max_open_jobs=20} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_], term: 2, version: 18, reason: master node changed {previous [], current [{cb3184021e94}{ZnuwsNZIQ1yATwZP1kUJ5g}{aiJTDRlMQDmnDDSIQ0BhSg}{172.19.0.2}{172.19.0.2:9300}{ml.machine_memory=504868864, xpack.installed=true, ml.max_open_jobs=20}]}"  }
{"type": "server", "timestamp": "2019-07-24T07:09:52,500+0000", "level": "INFO", "component": "o.e.c.s.ClusterApplierService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94",  "message": "master node changed {previous [], current [{cb3184021e94}{ZnuwsNZIQ1yATwZP1kUJ5g}{aiJTDRlMQDmnDDSIQ0BhSg}{172.19.0.2}{172.19.0.2:9300}{ml.machine_memory=504868864, xpack.installed=true, ml.max_open_jobs=20}]}, term: 2, version: 18, reason: Publication{term=2, version=18}"  }
{"type": "server", "timestamp": "2019-07-24T07:09:52,705+0000", "level": "INFO", "component": "o.e.h.AbstractHttpServerTransport", "cluster.name": "docker-cluster", "node.name": "cb3184021e94", "cluster.uuid": "vOjTUfOHQZORLeDRFKbV0w", "node.id": "ZnuwsNZIQ1yATwZP1kUJ5g",  "message": "publish_address {172.19.0.2:9200}, bound_addresses {0.0.0.0:9200}"  }
{"type": "server", "timestamp": "2019-07-24T07:09:52,706+0000", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "cb3184021e94", "cluster.uuid": "vOjTUfOHQZORLeDRFKbV0w", "node.id": "ZnuwsNZIQ1yATwZP1kUJ5g",  "message": "started"  }
{"type": "server", "timestamp": "2019-07-24T07:09:53,492+0000", "level": "INFO", "component": "o.e.l.LicenseService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94", "cluster.uuid": "vOjTUfOHQZORLeDRFKbV0w", "node.id": "ZnuwsNZIQ1yATwZP1kUJ5g",  "message": "license [5efeffc9-8e49-42d1-a8be-92343d8b84c5] mode [basic] - valid"  }
{"type": "server", "timestamp": "2019-07-24T07:09:53,536+0000", "level": "INFO", "component": "o.e.g.GatewayService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94", "cluster.uuid": "vOjTUfOHQZORLeDRFKbV0w", "node.id": "ZnuwsNZIQ1yATwZP1kUJ5g",  "message": "recovered [1] indices into cluster_state"  }
{"type": "server", "timestamp": "2019-07-24T07:09:55,342+0000", "level": "INFO", "component": "o.e.c.r.a.AllocationService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94", "cluster.uuid": "vOjTUfOHQZORLeDRFKbV0w", "node.id": "ZnuwsNZIQ1yATwZP1kUJ5g",  "message": "Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[.monitoring-es-7-2019.07.24][0]] ...])."  }
{"type": "server", "timestamp": "2019-07-24T07:10:03,469+0000", "level": "INFO", "component": "o.e.m.j.JvmGcMonitorService", "cluster.name": "docker-cluster", "node.name": "cb3184021e94", "cluster.uuid": "vOjTUfOHQZORLeDRFKbV0w", "node.id": "ZnuwsNZIQ1yATwZP1kUJ5g",  "message": "[gc][12] overhead, spent [278ms] collecting in the last [1s]"  }
Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
output:
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 89522176 bytes for committing reserved memory.
# An error report file with more information is saved as:
# logs/hs_err_pid100.log
error:
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000faaa0000, 89522176, 0) failed; error='Not enough space' (errno=12)
	at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:111)
	at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:79)
	at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:57)
	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:89)
```

**Comment by antoineco** [comment]
@FrameBassman the host requirements are documented [right here](https://github.com/deviantony/docker-elk/blob/master/README.md#host-setup).

**Comment by FrameBassman** [comment]
My issue is reproduced on machine with 1Gb RAM

**Comment by antoineco** [comment]
What else is running on the machine? Did you reset your changes? Elasticsearch won't run with a 128MB heap.

**Comment by FrameBassman** [comment]
Only docker is running on this machine
I just clone this repo and run `docker-compose up -d`

**Comment by antoineco** [comment]
I couldn't reproduce inside a VM with 1 GiB of RAM. But to be fair, my RAM is extended by the equivalent swap space, which is used quite extensively (compare swap usage before and after starting the stack). I think you are right, our current minimum of 1 GB is not realistic.

```console
docker-desktop:~# free -m

             total       used       free     shared    buffers     cached
Mem:           992        903         89          0          2        621
-/+ buffers/cache:        279        713
Swap:         1023          0       1023
```

```console
mac:/git/deviantony/docker-elk$ docker-compose up -d

Creating network "docker-elk_elk" with driver "bridge"
Creating docker-elk_elasticsearch_1 ... done
Creating docker-elk_kibana_1        ... done
Creating docker-elk_logstash_1      ... done
```

```console
mac:/git/deviantony/docker-elk$ docker-compose ps

           Name                         Command               State                            Ports
------------------------------------------------------------------------------------------------------------------------------
docker-elk_elasticsearch_1   /usr/local/bin/docker-entr ...   Up      0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp
docker-elk_kibana_1          /usr/local/bin/kibana-docker     Up      0.0.0.0:5601->5601/tcp
docker-elk_logstash_1        /usr/local/bin/docker-entr ...   Up      0.0.0.0:5000->5000/tcp, 5044/tcp, 0.0.0.0:9600->9600/tcp
```

```console
mac:/git/deviantony/docker-elk$ curl -D- localhost:9200 -u elastic:changeme

HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 508

{
  "name" : "e1b4e662d8a9",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "IDs5C5ZYQ8SdmaNcw8PaHg",
  "version" : {
    "number" : "7.2.0",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "508c38a",
    "build_date" : "2019-06-20T15:54:18.811730Z",
    "build_snapshot" : false,
    "lucene_version" : "8.0.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

```console
docker-desktop:~# free -m

             total       used       free     shared    buffers     cached
Mem:           992        932         60          0          1         65
-/+ buffers/cache:        865        127
Swap:         1023        752        271
```

```console
docker-desktop:~# ps -o pid,rss,vsz,args

# elasticsearch
PID   RSS  VSZ  COMMAND
 2756 423m 2.8g /usr/share/elasticsearch/jdk/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Des.netw
orkaddress.cach

# kibana
 3003  53m 1.6g /usr/share/kibana/bin/../node/bin/node --no-warnings --max-http-header-size=65536 /usr/share/kibana/bin/../src/cli --cpu.cgroup.path.override=/ --cpuacct.cgroup.path.overrid

# logstash
 3088 278m 2.8g /bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djru
```

**Comment by FrameBassman** [comment]
This is my metrics:
```bash
root@cs626560 ~ # free -m
              total        used        free      shared  buff/cache   available
Mem:            985         109         169           0         706         719
Swap:           138           0         138
```
```bash
root@cs626560 ~ # ps -o pid,rss,vsz,args
  PID   RSS    VSZ COMMAND
12322  4952  24188 -bash
12338  1552  30432 ps -o pid,rss,vsz,args
```

**Comment by antoineco** [comment]
[This page](https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html) is very useful:
> Elasticsearch requires memory for purposes other than the JVM heap and it is important to leave space for this. For instance, Elasticsearch uses off-heap buffers for efficient network communication, relies on the operating system’s filesystem cache for efficient access to files, and the JVM itself requires some memory too. It is normal to observe the Elasticsearch process using more memory than the limit configured with the Xmx setting.

I'll bump the minimum requirement to *1.5 GB* (512 MB for the combined heap of Elasticsearch and Logstash, the same amount for off-heap buffers, and ~500 MB of head room for Kibana and OS processes).

Keep in mind that this is an absolute minimum for running the stack and testing it with a small load only.
