### ISSUE TITLE
FATAL  ValidationError: child "elasticsearch" fails because ["hosts" is not allowed]

### ISSUE THREAD

**Issue by linyongfu2013** [deviantony/docker-elk#478]
### Problem description

Cloned the latest (master) repo for env 6.5.1 and docker-compose up
Kibana fails to start

FATAL ValidationError: child "elasticsearch" fails because ["hosts" is not allowed]

#### Stack configuration
no configuratoion changes, only change env to 6.5.1

#### Docker setup

```

Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:25:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

```

docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

```

#### Docker logs

```

[root@izwz93locplbdj7zd3ji7wz docker-elk]# docker-compose up
Creating network "docker-elk_elk" with driver "bridge"
Creating docker-elk_elasticsearch_1 ... done
Creating docker-elk_logstash_1      ... done
Creating docker-elk_kibana_1        ... done
Attaching to docker-elk_elasticsearch_1, docker-elk_kibana_1, docker-elk_logstash_1
elasticsearch_1  | Created elasticsearch keystore in /usr/share/elasticsearch/config
elasticsearch_1  | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
elasticsearch_1  | [2020-04-01T14:39:12,557][WARN ][o.e.c.l.LogConfigurator  ] [unknown] Some logging configurations have %marker but don't have %node_name. We will automatically add %node_name to the pattern to ease the migration for users who customize log4j2.properties but will stop this behavior in 7.0. You should manually replace `%node_name` with `[%node_name]%marker ` in these locations:
elasticsearch_1  |   /usr/share/elasticsearch/config/log4j2.properties
elasticsearch_1  | [2020-04-01T14:39:14,728][INFO ][o.e.e.NodeEnvironment    ] [YSPmDMW] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/vda1)]], net usable_space [6.6gb], net total_space [39.2gb], types [ext4]
elasticsearch_1  | [2020-04-01T14:39:14,729][INFO ][o.e.e.NodeEnvironment    ] [YSPmDMW] heap size [247.5mb], compressed ordinary object pointers [true]
elasticsearch_1  | [2020-04-01T14:39:14,886][INFO ][o.e.n.Node               ] [YSPmDMW] node name derived from node ID [YSPmDMWFTYqPCAez819IaA]; set [node.name] to override
elasticsearch_1  | [2020-04-01T14:39:14,886][INFO ][o.e.n.Node               ] [YSPmDMW] version[6.5.1], pid[1], build[default/tar/8c58350/2018-11-16T02:22:42.182257Z], OS[Linux/3.10.0-957.21.3.el7.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/11.0.1/11.0.1+13]
elasticsearch_1  | [2020-04-01T14:39:14,887][INFO ][o.e.n.Node               ] [YSPmDMW] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch.igYIxnQK, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Djava.locale.providers=COMPAT, -XX:UseAVX=2, -Des.cgroups.hierarchy.override=/, -Xmx256m, -Xms256m, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=tar]
elasticsearch_1  | [2020-04-01T14:39:22,657][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded module [aggs-matrix-stats]
elasticsearch_1  | [2020-04-01T14:39:22,658][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded module [analysis-common]
elasticsearch_1  | [2020-04-01T14:39:22,658][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded module [ingest-common]
elasticsearch_1  | [2020-04-01T14:39:22,658][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded module [lang-expression]
elasticsearch_1  | [2020-04-01T14:39:22,658][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded module [lang-mustache]
elasticsearch_1  | [2020-04-01T14:39:22,658][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded module [lang-painless]
elasticsearch_1  | [2020-04-01T14:39:22,658][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded module [mapper-extras]
elasticsearch_1  | [2020-04-01T14:39:22,658][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded module [parent-join]
elasticsearch_1  | [2020-04-01T14:39:22,658][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded module [percolator]
elasticsearch_1  | [2020-04-01T14:39:22,658][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded module [rank-eval]
elasticsearch_1  | [2020-04-01T14:39:22,662][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded module [reindex]
elasticsearch_1  | [2020-04-01T14:39:22,662][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded module [repository-url]
elasticsearch_1  | [2020-04-01T14:39:22,662][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded module [transport-netty4]
elasticsearch_1  | [2020-04-01T14:39:22,662][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded module [tribe]
elasticsearch_1  | [2020-04-01T14:39:22,663][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded module [x-pack-ccr]
elasticsearch_1  | [2020-04-01T14:39:22,663][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded module [x-pack-core]
elasticsearch_1  | [2020-04-01T14:39:22,663][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded module [x-pack-deprecation]
elasticsearch_1  | [2020-04-01T14:39:22,663][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded module [x-pack-graph]
elasticsearch_1  | [2020-04-01T14:39:22,663][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded module [x-pack-logstash]
elasticsearch_1  | [2020-04-01T14:39:22,663][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded module [x-pack-ml]
elasticsearch_1  | [2020-04-01T14:39:22,663][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded module [x-pack-monitoring]
elasticsearch_1  | [2020-04-01T14:39:22,663][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded module [x-pack-rollup]
elasticsearch_1  | [2020-04-01T14:39:22,663][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded module [x-pack-security]
elasticsearch_1  | [2020-04-01T14:39:22,663][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded module [x-pack-sql]
elasticsearch_1  | [2020-04-01T14:39:22,664][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded module [x-pack-upgrade]
elasticsearch_1  | [2020-04-01T14:39:22,664][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded module [x-pack-watcher]
elasticsearch_1  | [2020-04-01T14:39:22,664][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded plugin [ingest-geoip]
elasticsearch_1  | [2020-04-01T14:39:22,664][INFO ][o.e.p.PluginsService     ] [YSPmDMW] loaded plugin [ingest-user-agent]
kibana_1         | {"type":"error","@timestamp":"2020-04-01T14:39:34Z","tags":["fatal","root"],"pid":1,"level":"fatal","error":{"message":"child \"elasticsearch\" fails because [\"hosts\" is not allowed]","name":"ValidationError","stack":"ValidationError: child \"elasticsearch\" fails because [\"hosts\" is not allowed]\n    at Object.exports.process (/usr/share/kibana/node_modules/joi/lib/errors.js:181:19)\n    at internals.Object._validateWithOptions (/usr/share/kibana/node_modules/joi/lib/any.js:651:31)\n    at module.exports.internals.Any.root.validate (/usr/share/kibana/node_modules/joi/lib/index.js:121:23)\n    at Config._commit (/usr/share/kibana/src/server/config/config.js:138:35)\n    at Config.set (/usr/share/kibana/src/server/config/config.js:108:10)\n    at Config.extendSchema (/usr/share/kibana/src/server/config/config.js:81:10)\n    at extendConfigService (/usr/share/kibana/src/plugin_discovery/plugin_config/extend_config_service.js:45:10)\n    at <anonymous>"},"message":"child \"elasticsearch\" fails because [\"hosts\" is not allowed]"}
kibana_1         |
kibana_1         |  FATAL  ValidationError: child "elasticsearch" fails because ["hosts" is not allowed]
kibana_1         |
docker-elk_kibana_1 exited with code 1
elasticsearch_1  | [2020-04-01T14:39:38,320][INFO ][o.e.x.s.a.s.FileRolesStore] [YSPmDMW] parsed [0] roles from file [/usr/share/elasticsearch/config/roles.yml]
elasticsearch_1  | [2020-04-01T14:39:39,803][INFO ][o.e.x.m.j.p.l.CppLogMessageHandler] [YSPmDMW] [controller/238] [Main.cc@109] controller (64 bit): Version 6.5.1 (Build 1c5fe241dd9aea) Copyright (c) 2018 Elasticsearch BV
elasticsearch_1  | [2020-04-01T14:39:41,368][INFO ][o.e.d.DiscoveryModule    ] [YSPmDMW] using discovery type [single-node] and host providers [settings]
elasticsearch_1  | [2020-04-01T14:39:43,267][INFO ][o.e.n.Node               ] [YSPmDMW] initialized
elasticsearch_1  | [2020-04-01T14:39:43,267][INFO ][o.e.n.Node               ] [YSPmDMW] starting ...
elasticsearch_1  | [2020-04-01T14:39:43,642][INFO ][o.e.t.TransportService   ] [YSPmDMW] publish_address {172.21.0.2:9300}, bound_addresses {0.0.0.0:9300}
elasticsearch_1  | [2020-04-01T14:39:43,845][INFO ][o.e.x.s.t.n.SecurityNetty4HttpServerTransport] [YSPmDMW] publish_address {172.21.0.2:9200}, bound_addresses {0.0.0.0:9200}
elasticsearch_1  | [2020-04-01T14:39:43,846][INFO ][o.e.n.Node               ] [YSPmDMW] started
elasticsearch_1  | [2020-04-01T14:39:46,099][INFO ][o.e.l.LicenseService     ] [YSPmDMW] license [04902950-1156-4fa4-b012-38b626f8d5ae] mode [basic] - valid
elasticsearch_1  | [2020-04-01T14:39:46,163][INFO ][o.e.g.GatewayService     ] [YSPmDMW] recovered [2] indices into cluster_state
elasticsearch_1  | [2020-04-01T14:39:48,104][INFO ][o.e.c.r.a.AllocationService] [YSPmDMW] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[inner_comment][1]] ...]).
^@elasticsearch_1  | [2020-04-01T14:39:53,994][INFO ][o.e.c.m.MetaDataCreateIndexService] [YSPmDMW] [.monitoring-es-6-2020.04.01] creating index, cause [auto(bulk api)], templates [.monitoring-es], shards [1]/[0], mappings [doc]
logstash_1       | Sending Logstash logs to /usr/share/logstash/logs which is now configured via log4j2.properties
logstash_1       | [2020-04-01T14:39:56,161][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ArgumentError: Setting "xpack.monitoring.elasticsearch.hosts" hasn't been registered>, :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/settings.rb:36:in `get_setting'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:69:in `set_value'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:88:in `block in merge'", "org/jruby/RubyHash.java:1343:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:88:in `merge'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:137:in `validate_all'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:278:in `execute'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:237:in `run'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/usr/share/logstash/lib/bootstrap/environment.rb:73:in `<main>'"]}
logstash_1       | [2020-04-01T14:39:56,198][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit
docker-elk_logstash_1 exited with code 1

```

**Comment by antoineco** [comment]
@linyongfu2013 thanks for including all the requested info 💯 

To use Elastic `6.x` you should actually use the branch dedicated to that major version, as described in [Usage > Version selection](https://github.com/deviantony/docker-elk#version-selection)

Try this (you need to do this only once):
```
$ git checkout release-6.x
```
Then:
```
$ docker-compose build
$ docker-compose build up
```

**Comment by linyongfu2013** [comment]
@antoineco thank u so much, i did not notice that. i will try it now.

and one more thing , does this version include the xpack, i don't need it , do i need to add the remove xpack command to the configuration file ?

**Comment by linyongfu2013** [comment]
oops~~, still not working, same exception..

**Comment by antoineco** [comment]
> does this version include the xpack

Yes, this version includes the same X-Pack features as `7.x`.

If you navigate to the branch with your web browser ([here](https://github.com/deviantony/docker-elk/tree/release-6.x)), you will see the updated instructions for that particular version. Most of the things should be identical between `6.x` and  `7.x`.

> still not working, same exception

Can you please show the output of the `git branch` command? Did you run `docker-compose build`? (very important)

**Comment by linyongfu2013** [comment]
> Can you please show the output of the `git branch` command? Did you run `docker-compose build`? (very important)

My cloud server doesn't have git , so i use download zip, and i am sure it's 6.x release version.
And i did run `docker-compose build`, but it did not take much time

```
[root@izwz93locplbdj7zd3ji7wz docker-elk]# docker-compose build
cerebro uses an image, skipping
Building elasticsearch
Step 1/2 : ARG ELK_VERSION
Step 2/2 : FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
 ---> 32f93c89076d
Successfully built 32f93c89076d
Successfully tagged docker-elk_elasticsearch:latest
Building logstash
Step 1/2 : ARG ELK_VERSION
Step 2/2 : FROM docker.elastic.co/logstash/logstash:${ELK_VERSION}
 ---> 2f9354bb806a
Successfully built 2f9354bb806a
Successfully tagged docker-elk_logstash:latest
Building kibana
Step 1/2 : ARG ELK_VERSION
Step 2/2 : FROM docker.elastic.co/kibana/kibana:${ELK_VERSION}
 ---> afcfde4729b0
Successfully built afcfde4729b0
Successfully tagged docker-elk_kibana:latest
```

**Comment by linyongfu2013** [comment]
for version 6.5 and below,  the `kibana.yml` configuration should be `elasticsearch.url: ""` , not `elasticsearch.hosts: []`
problem solved.

**Comment by linyongfu2013** [comment]
One more thing, i add the remove xpack command to each DockerFile, run build, throw exception, it says the xpack plugin cannot be removed

```
ERROR: plugin [x-pack] not found; run 'elasticsearch-plugin list' to get list of installed plugins
ERROR: Service 'elasticsearch' failed to build: The command '/bin/sh -c elasticsearch-plugin remove x-pack' returned a non-zero code: 78

Unable to remove plugin because of error: "You are using the standard distribution of Kibana.  Please install the OSS-only distribution to remove X-Pack features."
ERROR: Service 'kibana' failed to build: The command '/bin/sh -c kibana-plugin remove x-pack' returned a non-zero code: 74

As of 6.3+ X-Pack is part of the default distribution and cannot be uninstalled;
to remove all X-Pack features, you must install the OSS-only distribution of
Logstash.
ERROR: Operation aborted, cannot remove plugin., message: x-pack not a removable plugin

```

does that mean i have to live with the error logs when the trial license expired ?

**Comment by antoineco** [comment]
Sorry you're right, I missed an important detail here: you're using 6.5 and not 6.8. A lot of things changed in 6.7 if I remember correctly.

The `elasticsearch.url` option is one of them, but also back then X-Pack was not yet a free add-on, so Elastic used to release 2 flavors of container images. The ones without X-Pack have the `-oss` suffix in their name.

Here's the state of the repo at the time 6.5 was the current series: https://github.com/deviantony/docker-elk/tree/a710c496
Check the images inside Dockerfiles.

By the way, is there any reason for you not to use the current 6.x version?

**Comment by linyongfu2013** [comment]
> By the way, is there any reason for you not to use the current 6.x version?

Company use version 6.5.1 for almost a year, no plan to upgrade yet, not before i have time to get familar to new version.

Thanks .

**Comment by antoineco** [comment]
That's alright, the link I sent you at this specific commit should give you a functional 6.5.4 stack without any X-Pack included.
