### ISSUE TITLE
Could not load plugin descriptor for plugin directory [.DS_Store]

### ISSUE THREAD

**Issue by linyongfu2013** [deviantony/docker-elk#487]
### Problem description
MacOS using the latest version,  and analysis-ik plugin, start up fail.

### Extra information

```
➜  docker-elk git:(master) ✗ tree
.
├── LICENSE
├── README.md
├── docker-compose.yml
├── docker-stack.yml
├── elasticsearch
│   ├── Dockerfile
│   ├── config
│   │   └── elasticsearch.yml
│   └── plugins
│       └── analysis-ik
│           ├── commons-codec-1.9.jar
│           ├── commons-logging-1.2.jar
│           ├── config
│           │   ├── IKAnalyzer.cfg.xml
│           │   ├── extra_main.dic
│           │   ├── extra_single_word.dic
│           │   ├── extra_single_word_full.dic
│           │   ├── extra_single_word_low_freq.dic
│           │   ├── extra_stopword.dic
│           │   ├── main.dic
│           │   ├── preposition.dic
│           │   ├── quantifier.dic
│           │   ├── stopword.dic
│           │   ├── suffix.dic
│           │   └── surname.dic
│           ├── elasticsearch-analysis-ik-7.6.0.jar
│           ├── httpclient-4.5.2.jar
│           ├── httpcore-4.4.4.jar
│           ├── plugin-descriptor.properties
│           └── plugin-security.policy
├── extensions
│   ├── README.md
│   ├── apm-server
│   │   ├── Dockerfile
│   │   ├── README.md
│   │   ├── apm-server-compose.yml
│   │   └── config
│   │       └── apm-server.yml
│   ├── app-search
│   │   ├── Dockerfile
│   │   ├── README.md
│   │   ├── app-search-compose.yml
│   │   └── config
│   │       └── app-search.yml
│   ├── curator
│   │   ├── Dockerfile
│   │   ├── README.md
│   │   ├── config
│   │   │   ├── curator.yml
│   │   │   └── delete_log_files_curator.yml
│   │   ├── curator-compose.yml
│   │   └── entrypoint.sh
│   └── logspout
│       ├── Dockerfile
│       ├── README.md
│       ├── build.sh
│       ├── logspout-compose.yml
│       └── modules.go
├── kibana
│   ├── Dockerfile
│   └── config
│       └── kibana.yml
└── logstash
    ├── Dockerfile
    ├── config
    │   └── logstash.yml
    └── pipeline
        └── logstash.conf
```

#### Stack configuration
add analysis-ik plugin command to elasticsearch Dockerfile.

```
  1 ARG ELK_VERSION
  2
  3 # https://www.docker.elastic.co/
  4 FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
  5
  6 # Add your elasticsearch plugins setup here
  7 # Example: RUN elasticsearch-plugin install analysis-icu
  8
  9 COPY plugins plugins
```

#### Docker setup

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

#### Docker logs

```

elasticsearch_1  | {"type": "server", "timestamp": "2020-04-20T12:33:25,339Z", "level": "ERROR", "component": "o.e.b.ElasticsearchUncaughtExceptionHandler", "cluster.name": "docker-elk", "node.name": "8ac6e9abc043", "message": "uncaught exception in thread [main]",
elasticsearch_1  | "stacktrace": ["org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Could not load plugin descriptor for plugin directory [.DS_Store]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:174) ~[elasticsearch-7.6.0.jar:7.6.0]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161) ~[elasticsearch-7.6.0.jar:7.6.0]",
elasticsearch_1  | "at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.6.0.jar:7.6.0]",
elasticsearch_1  | "at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125) ~[elasticsearch-cli-7.6.0.jar:7.6.0]",
elasticsearch_1  | "at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.6.0.jar:7.6.0]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126) ~[elasticsearch-7.6.0.jar:7.6.0]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.6.0.jar:7.6.0]",
elasticsearch_1  | "Caused by: java.lang.IllegalStateException: Could not load plugin descriptor for plugin directory [.DS_Store]",
elasticsearch_1  | "at org.elasticsearch.plugins.PluginsService.readPluginBundle(PluginsService.java:401) ~[elasticsearch-7.6.0.jar:7.6.0]",
elasticsearch_1  | "at org.elasticsearch.plugins.PluginsService.findBundles(PluginsService.java:386) ~[elasticsearch-7.6.0.jar:7.6.0]",
elasticsearch_1  | "at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:379) ~[elasticsearch-7.6.0.jar:7.6.0]",
elasticsearch_1  | "at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:151) ~[elasticsearch-7.6.0.jar:7.6.0]",
elasticsearch_1  | "at org.elasticsearch.node.Node.<init>(Node.java:313) ~[elasticsearch-7.6.0.jar:7.6.0]",
elasticsearch_1  | "at org.elasticsearch.node.Node.<init>(Node.java:257) ~[elasticsearch-7.6.0.jar:7.6.0]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.6.0.jar:7.6.0]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.6.0.jar:7.6.0]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.6.0.jar:7.6.0]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.6.0.jar:7.6.0]",
elasticsearch_1  | "... 6 more",
elasticsearch_1  | "Caused by: java.nio.file.FileSystemException: /usr/share/elasticsearch/plugins/.DS_Store/plugin-descriptor.properties: Not a directory",
elasticsearch_1  | "at sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[?:?]",
elasticsearch_1  | "at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]",
elasticsearch_1  | "at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]",
elasticsearch_1  | "at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219) ~[?:?]",
elasticsearch_1  | "at java.nio.file.Files.newByteChannel(Files.java:374) ~[?:?]",
elasticsearch_1  | "at java.nio.file.Files.newByteChannel(Files.java:425) ~[?:?]",
elasticsearch_1  | "at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420) ~[?:?]",
elasticsearch_1  | "at java.nio.file.Files.newInputStream(Files.java:159) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:156) ~[elasticsearch-7.6.0.jar:7.6.0]",
elasticsearch_1  | "at org.elasticsearch.plugins.PluginsService.readPluginBundle(PluginsService.java:398) ~[elasticsearch-7.6.0.jar:7.6.0]",
elasticsearch_1  | "at org.elasticsearch.plugins.PluginsService.findBundles(PluginsService.java:386) ~[elasticsearch-7.6.0.jar:7.6.0]",
elasticsearch_1  | "at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:379) ~[elasticsearch-7.6.0.jar:7.6.0]",
elasticsearch_1  | "at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:151) ~[elasticsearch-7.6.0.jar:7.6.0]",
elasticsearch_1  | "at org.elasticsearch.node.Node.<init>(Node.java:313) ~[elasticsearch-7.6.0.jar:7.6.0]",
elasticsearch_1  | "at org.elasticsearch.node.Node.<init>(Node.java:257) ~[elasticsearch-7.6.0.jar:7.6.0]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.6.0.jar:7.6.0]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.6.0.jar:7.6.0]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.6.0.jar:7.6.0]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.6.0.jar:7.6.0]",
elasticsearch_1  | "... 6 more"] }
elasticsearch_1  | uncaught exception in thread [main]
elasticsearch_1  | java.lang.IllegalStateException: Could not load plugin descriptor for plugin directory [.DS_Store]
elasticsearch_1  | Likely root cause: java.nio.file.FileSystemException: /usr/share/elasticsearch/plugins/.DS_Store/plugin-descriptor.properties: Not a directory
elasticsearch_1  | 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
elasticsearch_1  | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
elasticsearch_1  | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
elasticsearch_1  | 	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
elasticsearch_1  | 	at java.base/java.nio.file.Files.newByteChannel(Files.java:374)
elasticsearch_1  | 	at java.base/java.nio.file.Files.newByteChannel(Files.java:425)
elasticsearch_1  | 	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
elasticsearch_1  | 	at java.base/java.nio.file.Files.newInputStream(Files.java:159)
elasticsearch_1  | 	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:156)
elasticsearch_1  | 	at org.elasticsearch.plugins.PluginsService.readPluginBundle(PluginsService.java:398)
elasticsearch_1  | 	at org.elasticsearch.plugins.PluginsService.findBundles(PluginsService.java:386)
elasticsearch_1  | 	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:379)
elasticsearch_1  | 	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:151)
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:313)
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:257)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
elasticsearch_1  | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
elasticsearch_1  | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
elasticsearch_1  | 	at org.elasticsearch.cli.Command.main(Command.java:90)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
elasticsearch_1  | For complete error details, refer to the log at /usr/share/elasticsearch/logs/docker-elk.log
kibana_1         | {"type":"log","@timestamp":"2020-04-20T12:33:25Z","tags":["info","plugins-service"],"pid":6,"message":"Plugin \"case\" is disabled."}
docker-elk_elasticsearch_1 exited with code 1


```

**Comment by antoineco** [comment]
macOS created some `.DS_Store` files that confuse Elasticsearch.

`rm plugins/.DS_Store` should solve your problem.

I will push a `.dockerignore` file to the repository so those files get ignored by default.

**Comment by antoineco** [comment]
@linyongfu2013 if you pull my latest commit your issue should go away.

**Comment by yueJ225v2** [comment]
> macOS 创建了一些`.DS_Store`混淆 Elasticsearch 的文件。
> 
> `rm plugins/.DS_Store`应该可以解决您的问题。
> 
> 我会将`.dockerignore`文件推送到存储库，以便默认情况下忽略这些文件。

nice
