### ISSUE TITLE
logstash add directory and file into container,  the owner is root , not logstash, cause logstash has no permission to execute pipeline

### ISSUE THREAD

**Issue by linyongfu2013** [deviantony/docker-elk#494]
### Problem description
logstash add directory and file into container,  the owner is root , not logstash, cause logstash has no permission to execute pipeline

#### Stack configuration
ELK_VERSION = 7.6.0

```
ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash:${ELK_VERSION}

COPY mysql mysql
COPY test test
```

#### Docker setup

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:25:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

```
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

#### Docker logs

```
logstash_1       | 2020-05-08T15:27:31.697921977Z [2020-05-08T15:27:31,697][ERROR][logstash.javapipeline    ][main] Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<Errno::EACCES: Permission denied - /usr/share/logstash/test/user.txt>, :backtrace=>["org/jruby/RubyFile.java:1295:in `delete'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-integration-jdbc-5.0.0/lib/logstash/plugin_mixins/jdbc/value_tracking.rb:112:in `clean'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-integration-jdbc-5.0.0/lib/logstash/plugin_mixins/jdbc/value_tracking.rb:56:in `common_set_initial'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-integration-jdbc-5.0.0/lib/logstash/plugin_mixins/jdbc/value_tracking.rb:65:in `set_initial'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-integration-jdbc-5.0.0/lib/logstash/plugin_mixins/jdbc/value_tracking.rb:34:in `initialize'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-integration-jdbc-5.0.0/lib/logstash/plugin_mixins/jdbc/value_tracking.rb:18:in `build_last_value_tracker'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-integration-jdbc-5.0.0/lib/logstash/inputs/jdbc.rb:240:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:200:in `block in register_plugins'", "org/jruby/RubyArray.java:1814:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:199:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:310:in `start_inputs'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:270:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:154:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:109:in `block in start'"], "pipeline.sources"=>["/usr/share/logstash/pipeline/logstash.conf", "/usr/share/logstash/pipeline/test-user.conf"], :thread=>"#<Thread:0x6aa0d005 run>"}
logstash_1       | 2020-05-08T15:27:31.706244026Z [2020-05-08T15:27:31,705][ERROR][logstash.agent           ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: PipelineAction::Create<main>, action_result: false", :backtrace=>nil}

```

##### Extra info
```
[vagrant@localhost docker-elk]$ docker exec -it b2851e8fc6f1 /bin/bash
bash-4.2$
bash-4.2$
bash-4.2$ ls -l
total 524
drwxrwsr-x. 2 logstash root       4096 Feb  6 01:51 bin
drwxrwsr-x. 1 logstash root        142 Feb  6 01:51 config
-rw-rw-r--. 1 logstash root       2276 Feb  6 01:43 CONTRIBUTORS
drwxrwsr-x. 1 logstash root         69 May  5 15:56 data
-rw-rw-r--. 1 logstash root       4028 Feb  6 01:44 Gemfile
-rw-rw-r--. 1 logstash root      22676 Feb  6 01:45 Gemfile.lock
drwxrwsr-x. 6 logstash root         84 Feb  6 01:51 lib
-rw-rw-r--. 1 logstash root      13675 Feb  6 01:43 LICENSE.txt
drwxrwsr-x. 4 logstash root         90 Feb  6 01:51 logstash-core
drwxrwsr-x. 3 logstash root         86 Feb  6 01:51 logstash-core-plugin-api
drwxrwsr-x. 4 logstash root         55 Feb  6 01:51 modules
drwxr-sr-x. 2 root     root         45 May  5 15:50 mysql
-rw-rw-r--. 1 logstash root     480537 Feb  6 01:43 NOTICE.TXT
drwxrwxr-x. 2 logstash logstash     27 May  8 15:33 pipeline
drwxr-sr-x. 2 root     root         22 May  5 15:50 test
drwxrwsr-x. 3 logstash root         30 Feb  6 01:51 tools
drwxrwsr-x. 4 logstash root         33 Feb  6 01:51 vendor
drwxrwsr-x. 9 logstash root        193 Feb  6 01:51 x-pack
```

you can see the mysql & test directory's owner are root , not logstash.

**Comment by antoineco** [comment]
`COPY --chown=logstash mysql mysql` is what you need here.

https://docs.docker.com/engine/reference/builder/#copy

**Comment by linyongfu2013** [comment]
rebuild the image, docker build logstash, not working, still is root:root

**Comment by linyongfu2013** [comment]
the strange thing is , same command works fine on elasticsearch, not using --chown option, why logstash has this issue?

**Comment by antoineco** [comment]
Works perfectly fine for me:
```console
$ docker-compose exec logstash ls -l
total 568
drwxrwsr-x 2 logstash root       4096 Mar 26 09:01 bin
drwxrwsr-x 1 logstash root       4096 Mar 26 09:02 config
-rw-rw-r-- 1 logstash root       2276 Mar 26 08:51 CONTRIBUTORS
drwxrwsr-x 2 logstash root       4096 Mar 26 08:51 data
-rw-rw-r-- 1 logstash root       4028 Mar 26 08:53 Gemfile
-rw-rw-r-- 1 logstash root      22676 Mar 26 08:53 Gemfile.lock
drwxrwsr-x 6 logstash root       4096 Mar 26 09:01 lib
-rw-rw-r-- 1 logstash root      13675 Mar 26 08:51 LICENSE.txt
drwxrwsr-x 4 logstash root       4096 Mar 26 09:01 logstash-core
drwxrwsr-x 3 logstash root       4096 Mar 26 09:01 logstash-core-plugin-api
drwxrwsr-x 4 logstash root       4096 Mar 26 09:01 modules
drwxr-sr-x 2 logstash logstash   4096 May  8 16:24 mysql    <------------------- owned by logstash
-rw-rw-r-- 1 logstash root     480537 Mar 26 08:51 NOTICE.TXT
drwxr-xr-x 2 logstash logstash   4096 Apr 21 07:30 pipeline
drwxrwsr-x 3 logstash root       4096 Mar 26 09:01 tools
drwxrwsr-x 4 logstash root       4096 Mar 26 09:01 vendor
drwxrwsr-x 9 logstash root       4096 Mar 26 09:01 x-pack
```
```console
$ ls -l logstash
total 16
drwxr-xr-x 2 acotten acotten 4096 Apr 21 09:30 config
drwxr-xr-x 2 acotten acotten 4096 May  8 18:22 mysql
drwxr-xr-x 2 acotten acotten 4096 Apr 21 09:30 pipeline
-rw-r--r-- 1 acotten acotten  241 May  8 18:21 Dockerfile
```
```diff
diff --git a/logstash/Dockerfile b/logstash/Dockerfile
index 6a444e7..f71e6c8 100644
--- a/logstash/Dockerfile
+++ b/logstash/Dockerfile
@@ -5,3 +5,5 @@ FROM docker.elastic.co/logstash/logstash:${ELK_VERSION}

 # Add your logstash plugins setup here
 # Example: RUN logstash-plugin install logstash-filter-json
+
+COPY --chown=logstash mysql mysql
```

**Comment by antoineco** [comment]
You need to run `docker-compose build logstash`, not `docker build logstash`. Not sure if that's what you meant.

**Comment by linyongfu2013** [comment]
```
[vagrant@localhost docker-elk]$ docker-compose build logstash
Building logstash
Step 1/4 : ARG ELK_VERSION
Step 2/4 : FROM docker.elastic.co/logstash/logstash:${ELK_VERSION}
 ---> 799d4bde3bdd
Step 3/4 : COPY --chown=logstash mysql mysql
 ---> Using cache
 ---> b9e41e367033
Step 4/4 : COPY --chown=logstash test test
 ---> Using cache
 ---> 20dd233b4cda
Successfully built 20dd233b4cda
```

could it be cache? how to disable cache, or build a new one?

**Comment by antoineco** [comment]
I think your cache is working just fine. You need to recreate the container with `docker-compose up`, that's it.

**Comment by linyongfu2013** [comment]
thank you so much, run docker-compose down, then docker-compose up, problem solved.

and btw,  the strange thing is , same command works fine on elasticsearch, not using --chown option, why logstash has this issue?

**Comment by antoineco** [comment]
My guess is that the Elasticsearch container runs with the `root` GID ([Dockerfile](https://github.com/elastic/elasticsearch/blob/f7e705d/distribution/docker/src/docker/Dockerfile#L112)), whereas the Logstash container runs with the user's GID, which is `logstash` (1000) in this case ([Dockerfile](https://github.com/elastic/logstash/blob/master/docker/templates/Dockerfile.j2#L58)).
