### ISSUE TITLE
EACCES: permission denied

### ISSUE THREAD

**Issue by jorgerabello3** [deviantony/docker-elk#517]
### Problem description

First I would like to thank you for making this code available.
Sorry for the silly question... but when I run docker-compose up I am encountering the following problem:

#### Docker logs

```
kibana_1         | FATAL CLI ERROR Error: EACCES: permission denied, open '/usr/share/kibana/config/kibana.yml'
kibana_1         |     at Object.openSync (fs.js:443:3)
elasticsearch_1  | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/config/elasticsearch.yml
elasticsearch_1  | 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
elasticsearch_1  | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
```
I cloned the repository and gave a docker-compose up directly from the code in the master. Can anybody help me please ? 

Thanks in advance

**Comment by antoineco** [comment]
Could you please provide details about your setup? What OS, what Docker version?

**Comment by antoineco** [comment]
Closing due to inactivity.
