### ISSUE TITLE
logstash http input plug-in not working

### ISSUE THREAD

**Issue by bhanupraveeng** [deviantony/docker-elk#530]
### Problem description

 I am using whole ELK stack and its working fine with all pipelines. After that i added http input plugin in logstash pipeline, added new port 8050 in docker-compose file as well. Stack is coming up and all other pipelines are working other than http. Not able to post any message. Please find the details below: 

#### Docker setup
docker-compose.yml

```
version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data     
      - type: bind
        source: /opt/esbackup
        target: /opt/esbackup
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx4g -Xms4g"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/
        target: /usr/share/logstash/config/
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
      - type: bind
        source: /var/log/logstash
        target: /var/log/logstash
        read_only: true
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "8050:8050/tcp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
  elasticsearch_backup:
```

httpinput.conf

```
input {
  http {
    host => paa120he
    port => 8050
    threads => 10
  }
}
```
output.conf

```
output 
{
	stdout {codec  => rubydebug}
   
	elasticsearch 
	{
	  hosts => "paa120he:9200"
	  manage_template => false
	  index => "%{[@metadata][target_index]}"
	}
  
}
```

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:45:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
```
docker-compose version 1.26.2, build unknown
docker-py version: 4.3.1
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017

```
Logstash output
```
2020-09-10T02:48:47.749998234Z   Pipeline_id:main
2020-09-10T02:48:47.750001504Z   Plugin: <LogStash::Inputs::Http host=>"lla10701", threads=>10, id=>"0e3c164641332e355c33e866acaafba3a56f5ba0dc8e26df734085ef376000e6", port=>8050, enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_3717e1cf-1b8a-4ccc-b63c-2526706cca0e", enable_metric=>true, charset=>"UTF-8">, ssl=>false, ssl_verify_mode=>"none", ssl_handshake_timeout=>10000, tls_min_version=>1, tls_max_version=>1.2, cipher_suites=>["TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384", "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384", "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256", "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"], additional_codecs=>{"application/json"=>"json"}, response_headers=>{"Content-Type"=>"text/plain"}, remote_host_target_field=>"host", request_headers_target_field=>"headers", max_pending_requests=>200, max_content_length=>104857600, response_code=>200, verify_mode=>"none">
2020-09-10T02:48:47.750009587Z   Error: event executor terminated
2020-09-10T02:48:47.750012015Z   Exception: Java::JavaUtilConcurrent::RejectedExecutionException
2020-09-10T02:48:47.750015139Z   Stack: io.netty.util.concurrent.SingleThreadEventExecutor.reject(io/netty/util/concurrent/SingleThreadEventExecutor.java:855)
2020-09-10T02:48:47.750019134Z io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(io/netty/util/concurrent/SingleThreadEventExecutor.java:328)
2020-09-10T02:48:47.750037451Z io.netty.util.concurrent.SingleThreadEventExecutor.addTask(io/netty/util/concurrent/SingleThreadEventExecutor.java:321)
2020-09-10T02:48:47.750043543Z io.netty.util.concurrent.SingleThreadEventExecutor.execute(io/netty/util/concurrent/SingleThreadEventExecutor.java:778)
2020-09-10T02:48:47.750047250Z io.netty.channel.AbstractChannel$AbstractUnsafe.register(io/netty/channel/AbstractChannel.java:479)
2020-09-10T02:48:47.750051270Z io.netty.channel.SingleThreadEventLoop.register(io/netty/channel/SingleThreadEventLoop.java:80)
2020-09-10T02:48:47.750056390Z io.netty.channel.SingleThreadEventLoop.register(io/netty/channel/SingleThreadEventLoop.java:74)
2020-09-10T02:48:47.750060542Z io.netty.channel.MultithreadEventLoopGroup.register(io/netty/channel/MultithreadEventLoopGroup.java:86)
2020-09-10T02:48:47.750063504Z io.netty.bootstrap.AbstractBootstrap.initAndRegister(io/netty/bootstrap/AbstractBootstrap.java:333)
2020-09-10T02:48:47.750065803Z io.netty.bootstrap.AbstractBootstrap.doBind(io/netty/bootstrap/AbstractBootstrap.java:282)
2020-09-10T02:48:47.750068105Z io.netty.bootstrap.AbstractBootstrap.bind(io/netty/bootstrap/AbstractBootstrap.java:278)
2020-09-10T02:48:47.750070365Z io.netty.bootstrap.AbstractBootstrap.bind(io/netty/bootstrap/AbstractBootstrap.java:260)
2020-09-10T02:48:47.750072706Z org.logstash.plugins.inputs.http.NettyHttpServer.run(org/logstash/plugins/inputs/http/NettyHttpServer.java:65)
2020-09-10T02:48:47.750075002Z jdk.internal.reflect.GeneratedMethodAccessor58.invoke(jdk/internal/reflect/GeneratedMethodAccessor58)
2020-09-10T02:48:47.750077282Z jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)
2020-09-10T02:48:47.750079612Z java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:566)
2020-09-10T02:48:47.750082016Z org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:441)
2020-09-10T02:48:47.750084343Z org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:305)
2020-09-10T02:48:47.750086667Z usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_input_minus_http_minus_3_dot_3_dot_4_minus_java.lib.logstash.inputs.http.run(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-http-3.3.4-java/lib/logstash/inputs/http.rb:152)
2020-09-10T02:48:47.750089342Z usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.inputworker(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:345)
2020-09-10T02:48:47.750091862Z usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$method$inputworker$0$__VARARGS__(usr/share/logstash/logstash_minus_core/lib/logstash//usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb)
2020-09-10T02:48:47.750094366Z usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.start_input(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:336)
2020-09-10T02:48:47.750096772Z org.jruby.RubyProc.call(org/jruby/RubyProc.java:318)
2020-09-10T02:48:47.750099000Z java.lang.Thread.run(java/lang/Thread.java:834)
2020-09-10T02:48:48.750423548Z [INFO ] 2020-09-10 02:48:48.750 [[main]<http] http - Starting http input listener {:address=>"lla10701:8050", :ssl=>"false"}
2020-09-10T02:48:48.750622000Z [WARN ] 2020-09-10 02:48:48.750 [[main]<http] AbstractChannel - Force-closing a channel whose registration task was not accepted by an event loop: [id: 0x63db48e9]
2020-09-10T02:48:48.751111918Z [ERROR] 2020-09-10 02:48:48.750 [[main]<http] rejectedExecution - Failed to submit a listener notification task. Event loop shut down?
2020-09-10T02:48:48.751124563Z java.util.concurrent.RejectedExecutionException: event executor terminated
2020-09-10T02:48:48.751129862Z 	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:855) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751134774Z 	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:328) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751139329Z 	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:321) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751143568Z 	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:778) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751146012Z 	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:768) [netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751148358Z 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:432) [netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751150763Z 	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103) [netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751159529Z 	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84) [netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751162035Z 	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1148) [netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751164431Z 	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:490) [netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751166873Z 	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80) [netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751169263Z 	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74) [netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751171647Z 	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86) [netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751174917Z 	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:333) [netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751180538Z 	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:282) [netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751185455Z 	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:278) [netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751189532Z 	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:260) [netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751200043Z 	at org.logstash.plugins.inputs.http.NettyHttpServer.run(NettyHttpServer.java:65) [logstash-input-http-3.3.4.jar:?]
2020-09-10T02:48:48.751205857Z 	at jdk.internal.reflect.GeneratedMethodAccessor58.invoke(Unknown Source) ~[?:?]
2020-09-10T02:48:48.751210213Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
2020-09-10T02:48:48.751214883Z 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
2020-09-10T02:48:48.751218282Z 	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:441) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751220647Z 	at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:305) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751222955Z 	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:32) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751225483Z 	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_input_minus_http_minus_3_dot_3_dot_4_minus_java.lib.logstash.inputs.http.RUBY$method$run$0(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-http-3.3.4-java/lib/logstash/inputs/http.rb:152) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751228468Z 	at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$method$inputworker$0(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:345) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751231070Z 	at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$method$inputworker$0$__VARARGS__(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751235104Z 	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:82) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751239620Z 	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:70) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751245005Z 	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:207) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751249041Z 	at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$block$start_input$1(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:336) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751253075Z 	at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:138) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751256822Z 	at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:58) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751260535Z 	at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:52) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751264158Z 	at org.jruby.runtime.Block.call(Block.java:139) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751267860Z 	at org.jruby.RubyProc.call(RubyProc.java:318) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751329340Z 	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:105) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751341409Z 	at java.lang.Thread.run(Thread.java:834) [?:?]
2020-09-10T02:48:48.751428513Z [ERROR] 2020-09-10 02:48:48.751 [[main]<http] rejectedExecution - Failed to submit a listener notification task. Event loop shut down?
2020-09-10T02:48:48.751445082Z java.util.concurrent.RejectedExecutionException: event executor terminated
2020-09-10T02:48:48.751447763Z 	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:855) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751450198Z 	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:328) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751452623Z 	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:321) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751455134Z 	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:778) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751457512Z 	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:768) [netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751459864Z 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:432) [netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751462224Z 	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121) [netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751464783Z 	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:987) [netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751467183Z 	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:491) [netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751469543Z 	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80) [netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751471903Z 	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74) [netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751474596Z 	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86) [netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751478860Z 	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:333) [netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751483286Z 	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:282) [netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751488699Z 	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:278) [netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751493628Z 	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:260) [netty-all-4.1.30.Final.jar:4.1.30.Final]
2020-09-10T02:48:48.751498003Z 	at org.logstash.plugins.inputs.http.NettyHttpServer.run(NettyHttpServer.java:65) [logstash-input-http-3.3.4.jar:?]
2020-09-10T02:48:48.751502343Z 	at jdk.internal.reflect.GeneratedMethodAccessor58.invoke(Unknown Source) ~[?:?]
2020-09-10T02:48:48.751512902Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
2020-09-10T02:48:48.751518255Z 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
2020-09-10T02:48:48.751523212Z 	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:441) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751526331Z 	at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:305) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751528658Z 	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:32) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751531082Z 	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_input_minus_http_minus_3_dot_3_dot_4_minus_java.lib.logstash.inputs.http.RUBY$method$run$0(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-http-3.3.4-java/lib/logstash/inputs/http.rb:152) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751533889Z 	at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$method$inputworker$0(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:345) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751536502Z 	at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$method$inputworker$0$__VARARGS__(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751539026Z 	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:82) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751541343Z 	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:70) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751543825Z 	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:207) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751562005Z 	at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$block$start_input$1(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:336) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751575619Z 	at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:138) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751580922Z 	at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:58) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751584952Z 	at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:52) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751588955Z 	at org.jruby.runtime.Block.call(Block.java:139) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751592870Z 	at org.jruby.RubyProc.call(RubyProc.java:318) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751597292Z 	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:105) [jruby-complete-9.2.11.1.jar:?]
2020-09-10T02:48:48.751601671Z 	at java.lang.Thread.run(Thread.java:834) [?:?]
2020-09-10T02:48:48.752028388Z [ERROR] 2020-09-10 02:48:48.751 [[main]<http] javapipeline - A plugin had an unrecoverable error. Will restart this plugin.



```

**Comment by antoineco** [comment]
Thanks for the detailed issue report @bhanupraveeng  🙌 

`host => paa120he` is not a valid host in your input. In general you should _not_ have to define the `host` parameter inside a container. Just remove it or set it to `0.0.0.0` (the default) and it will simply listen on the container's network interface.

I also see you changed the host in the Elasticsearch output to `hosts => "paa120he:9200"`, but this is unlikely to remain stable when containers get re-created. The default value of `hosts => "elasticsearch:9200"` ensures that the IP address of Elasticsearch will _always_ be resolved.

**Comment by bhanupraveeng** [comment]
Thanks a lot Antoine..After your suggested changes, it worked fine.
