### ISSUE TITLE
Logstash does not start

### ISSUE THREAD

**Issue by adouren** [deviantony/docker-elk#636]
Hi,

### Problem description

Logstash does not start

DOCKER-STACK.yml
```yaml
version: '3.3'
# 
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    ports:
      - "6892:9200"
      - "6893:9300"
      # - "6844:5044"
    configs:
      - source: elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
      # Force publishing on the 'elk' overlay.
      network.publish_host: _eth0_
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.elk == true]
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 120s

  logstash:
    image: docker.elastic.co/logstash/logstash:7.13.4
    ports:
      - "6850:5000"
      - "6896:9600"
    configs:
      - source: logstash.yml
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.elk == true]
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 120s

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.4
    ports:
      - "6856:5601"
    configs:
      - source: kibana.yml
        target: /usr/share/kibana/config/kibana.yml
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.elk == true]
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 120s

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.14.1 
    ports:
      - "6844:5044"
    configs:
      - source: filebeat.yml
        target: /usr/share/filebeat/config/filebeat.yml
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.elk == true]
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 120s

configs:
  elasticsearch.yml:
    external: true
  logstash.yml:
    external: true
  logstash.conf:
    external: true
  kibana.yml:
    external: true
  filebeat.yml:
    external: true
    
networks:
  elk:
    driver: overlay
```

FILEBEAT.yml
```yaml
filebeat.config:
  modules:
    # path: ${path.config}/modules.d/*.yml
    path: docker-elk-main/filebeat/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${elasticsearch:9200}'
  username: '${elastic:}'
  password: '${changeme:}'
setup.kibana:
  host: "kibana:5601"
```

FILEBEAT/MODULE.D/apache.yml
```yaml
#=========================== Filebeat prospectors =============================

# Each - is a prospector. Most options can be set at the prospector level, so
# you can use different prospectors for various configurations.
# Below are the prospector specific configurations.

- type: log

  # Change to true to enable this prospector configuration.
  enabled: true

  # Paths that should be crawled and fetched. Glob based paths.
  paths:
    # - /var/log/tomcat8/access.log
    # - /data/elkstk/newdeviantony/logapache
    - /apache2
    
  fields:
    logType: apache_access-log
```

LOGSTASH.yml
```yaml
# ---
## Default Logstash configuration from Logstash base image.
## https://github.com/elastic/logstash/blob/master/docker/data/logstash/config/logstash-full.yml
#
http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:6892" ]

## X-Pack security credentials
#
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.username: elastic
xpack.monitoring.elasticsearch.password: changeme
```
```ruby
input {
  beats {
                port => "5044"
        }
}

filter {


grok {
  match => {
	"message" => [
  		"^\[%{HTTPDATE:timestamp}\] (?:-|%{IPORHOST:ipext1:ip})\, (?:-|%{IPORHOST:ipext2:ip})\, (?:-|%{IPORHOST:ipclient:ip}) (?:-|%{IPORHOST:ipvip:ip}) - (?:-|%{USER:idep}) (?:%{WORD:verb}) %{NOTSPACE:request1} HTTP/%{NUMBER:httpversion} %{NUMBER:response} (?:-|%{NUMBER:taille:int}) (?:-|%{NUMBER:duree:int}) (?: \" \"| - |%{NOTSPACE:request2}) (?:-|%{GREEDYDATA:message})",
		"^\[%{HTTPDATE:timestamp}\] (?:-|%{IPORHOST:ipclient:ip}) (?:-|%{IPORHOST:ipvip:ip}) - (?:-|%{USER:idep}) (?:%{WORD:verb}) %{NOTSPACE:request1} HTTP/%{NUMBER:httpversion} %{NUMBER:response} (?:-|%{NUMBER:taille:int}) (?:-|%{NUMBER:duree:int}) (?: \" \"| - |%{NOTSPACE:request2}) (?:-|%{GREEDYDATA:message})" 
		]
  }
 } 
 
date {
        match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
	target => "@timestamp"
    }

if [request2] != "-" {
	mutate {
		copy => { "request2" => "request2_tmp" }
	}

	mutate {
		split => ["request2_tmp", "/"]
		add_field => { "request3" => "%{request2_tmp[2]}" }
	}

	mutate {
		remove_field => [ "request2_tmp" ]
	}
} 
 
fingerprint {
    source => "message"
    target => "[@metadata][fingerprint]"
    method => "SHA256"
    key => "chorus"
    base64encode => true
    remove_field => [ "message" ]
  }
 
  
}
output {
  elasticsearch {
        hosts => [<%= @output_elasticsearch_hosts %>]
	index => "logstash_chorus_access-log_%{+YYYY.MM.dd}"
	document_id => "%{[@metadata][fingerprint]}"
  }
}
```

#### Docker setup

DOCKER VERSION
```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
```

#### Container logs

```
Using bundled JDK: /usr/share/logstash/jdk

OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.

Sending Logstash logs to /usr/share/logstash/logs which is now configured via log4j2.properties

[2021-11-05T14:02:15,126][INFO ][logstash.runner          ] Log4j configuration path used is: /usr/share/logstash/config/log4j2.properties

[2021-11-05T14:02:15,137][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.13.4", "jruby.version"=>"jruby 9.2.16.0 (2.5.7) 2021-03-03 f82228dc32 OpenJDK 64-Bit Server VM 11.0.11+9 on 11.0.11+9 +indy +jit [linux-x86_64]"}

[2021-11-05T14:02:15,155][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.queue", :path=>"/usr/share/logstash/data/queue"}

[2021-11-05T14:02:15,164][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.dead_letter_queue", :path=>"/usr/share/logstash/data/dead_letter_queue"}

[2021-11-05T14:02:15,482][INFO ][logstash.agent           ] No persistent UUID file found. Generating new UUID {:uuid=>"9a8c7ffe-b38a-44af-b0a2-1f02bf27ec94", :path=>"/usr/share/logstash/data/uuid"}

[2021-11-05T14:02:15,973][WARN ][deprecation.logstash.monitoringextension.pipelineregisterhook] Internal collectors option for Logstash monitoring is deprecated and targeted for removal in the next major version.

Please configure Metricbeat to monitor Logstash. Documentation can be found at: 

https://www.elastic.co/guide/en/logstash/current/monitoring-with-metricbeat.html

[2021-11-05T14:02:16,330][WARN ][deprecation.logstash.outputs.elasticsearch] Relying on default value of `pipeline.ecs_compatibility`, which may change in a future major release of Logstash. To avoid unexpected changes when upgrading Logstash, please explicitly declare your desired ECS Compatibility mode.

[2021-11-05T14:02:16,841][INFO ][logstash.licensechecker.licensereader] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://elastic:xxxxxx@elasticsearch:9200/]}}

[2021-11-05T14:02:17,253][WARN ][logstash.licensechecker.licensereader] Attempted to resurrect connection to dead ES instance, but got an error {:url=>"http://elastic:xxxxxx@elasticsearch:9200/", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :message=>"Elasticsearch Unreachable: [http://elastic:xxxxxx@elasticsearch:9200/][Manticore::SocketException] Connection refused (Connection refused)"}

[2021-11-05T14:02:17,308][WARN ][logstash.licensechecker.licensereader] Marking url as dead. Last error: [LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError] Elasticsearch Unreachable: [http://elastic:xxxxxx@elasticsearch:9200/][Manticore::SocketException] Connection refused (Connection refused) {:url=>http://elastic:xxxxxx@elasticsearch:9200/, :error_message=>"Elasticsearch Unreachable: [http://elastic:xxxxxx@elasticsearch:9200/][Manticore::SocketException] Connection refused (Connection refused)", :error_class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError"}

[2021-11-05T14:02:17,314][ERROR][logstash.licensechecker.licensereader] Unable to retrieve license information from license server {:message=>"Elasticsearch Unreachable: [http://elastic:xxxxxx@elasticsearch:9200/][Manticore::SocketException] Connection refused (Connection refused)"}

[2021-11-05T14:02:17,382][ERROR][logstash.monitoring.internalpipelinesource] Failed to fetch X-Pack information from Elasticsearch. This is likely due to failure to reach a live Elasticsearch cluster.

[2021-11-05T14:02:17,809][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}

[2021-11-05T14:02:17,987][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of [ \\t\\r\\n], \"#\", \"input\", \"filter\", \"output\" at line 1, column 1 (byte 1)", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:32:in `compile_imperative'", "org/logstash/execution/AbstractPipelineExt.java:187:in `initialize'", "org/logstash/execution/JavaBasePipelineExt.java:72:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:47:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:389:in `block in converge_state'"]}

[2021-11-05T14:02:18,111][INFO ][logstash.runner          ] Logstash shut down.

[2021-11-05T14:02:18,137][FATAL][org.logstash.Logstash    ] Logstash stopped processing because of an error: (SystemExit) exit

org.jruby.exceptions.SystemExit: (SystemExit) exit

	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:747) ~[jruby-complete-9.2.16.0.jar:?]

	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:710) ~[jruby-complete-9.2.16.0.jar:?]

	at usr.share.logstash.lib.bootstrap.environment.<main>(/usr/share/logstash/lib/bootstrap/environment.rb:89) ~[?:?]
```

Best regard

Olivier

**Comment by antoineco** [comment]
**Note:** _I went ahead and edited your issue because all the config, logs, etc. were hidden inside HTML comments (`<!-- text -->`). Now they are visible. For the future: the correct way to wrap code blocks is ```` ``` text ``` ```` as shown in the description template that is pre-filled when you open a new issue._

The stack is deployed but Logstash fails to start, possibly due to a configuration error.
To me, this issue has more to do with the usage of Logstash than with docker-elk. Have you tried asking for help at https://discuss.elastic.co/? We can't possibly provide support for their massive software here, in this humble repository.

**Comment by adouren** [comment]
Ok, thanks ! I will be careful next time

No, i did not ask for help at https://discuss.elastic.co/? I will do it

Best regard

Olivier

**Comment by antoineco** [comment]
The error you shared, `:message=>"Expected one of [ \\t\\r\\n], \"#\", \"input\", \"filter\", \"output\" at line 1, column 1 (byte 1)"`, should give you a hint about where your error is.

Most likely a quote is missing, or some block isn't closed properly.

**Comment by antoineco** [comment]
Have you tried replacing `<%= @output_elasticsearch_hosts %>`? I assume this value was supposed to be populated by some template engine.

**Comment by adouren** [comment]
Hi antoineco,

Ok i'm looking at this

Thanks

**Comment by adouren** [comment]
Hi antoineco, 

Sorry, I'm a newbie to elk. 
what can I put to replace? 

Best regard

**Comment by antoineco** [comment]
I'd recommend reverting to the [default value](https://github.com/deviantony/docker-elk/blob/6f8117e2d82f2e847b7f50c532d8de13976cc304/logstash/pipeline/logstash.conf#L15).

**Comment by adouren** [comment]
Hi,

I redid the initial configuration. I think adding filebeat is problematic.

thank you

everybody
