### ISSUE TITLE
Crashing container logstash after any change in config file

### ISSUE THREAD

**Issue by nacesprin** [deviantony/docker-elk#660]
### Problem description

1) Open, save and close (with no changes) `/logstash/config/logstash.yml` or `/logstash/pipeline/logstash.conf`
2) Restart container to take the changes
3) Logstash crashes

### Extra information

This is the log of logstash after rebooting
```
Using bundled JDK: /usr/share/logstash/jdk


OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.


Sending Logstash logs to /usr/share/logstash/logs which is now configured via log4j2.properties


[2022-01-18T20:51:51,636][INFO ][logstash.runner          ] Log4j configuration path used is: /usr/share/logstash/config/log4j2.properties


[2022-01-18T20:51:51,654][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.16.2", "jruby.version"=>"jruby 9.2.20.1 (2.5.8) 2021-11-30 2a2962fbd1 OpenJDK 64-Bit Server VM 11.0.13+8 on 11.0.13+8 +indy +jit [linux-x86_64]"}


[2022-01-18T20:51:54,937][WARN ][deprecation.logstash.monitoringextension.pipelineregisterhook] Internal collectors option for Logstash monitoring is deprecated and may be removed in a future release.


Please configure Metricbeat to monitor Logstash. Documentation can be found at: 


https://www.elastic.co/guide/en/logstash/current/monitoring-with-metricbeat.html


[2022-01-18T20:51:55,727][WARN ][deprecation.logstash.codecs.plain] Relying on default value of `pipeline.ecs_compatibility`, which may change in a future major release of Logstash. To avoid unexpected changes when upgrading Logstash, please explicitly declare your desired ECS Compatibility mode.


[2022-01-18T20:51:55,866][WARN ][deprecation.logstash.outputs.elasticsearch] Relying on default value of `pipeline.ecs_compatibility`, which may change in a future major release of Logstash. To avoid unexpected changes when upgrading Logstash, please explicitly declare your desired ECS Compatibility mode.


[2022-01-18T20:51:56,529][INFO ][logstash.licensechecker.licensereader] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://elastic:xxxxxx@elasticsearch:9200/]}}


[2022-01-18T20:51:57,142][WARN ][logstash.licensechecker.licensereader] Restored connection to ES instance {:url=>"http://elastic:xxxxxx@elasticsearch:9200/"}


[2022-01-18T20:51:57,166][INFO ][logstash.licensechecker.licensereader] Elasticsearch version determined (7.16.2) {:es_version=>7}


[2022-01-18T20:51:57,174][WARN ][logstash.licensechecker.licensereader] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}


[2022-01-18T20:51:57,359][INFO ][logstash.monitoring.internalpipelinesource] Monitoring License OK


[2022-01-18T20:51:57,361][INFO ][logstash.monitoring.internalpipelinesource] Validated license for monitoring. Enabling monitoring pipeline.


[2022-01-18T20:51:58,139][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600, :ssl_enabled=>false}


[2022-01-18T20:52:01,120][INFO ][org.reflections.Reflections] Reflections took 451 ms to scan 1 urls, producing 119 keys and 417 values 


[2022-01-18T20:52:01,110][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of [ \\t\\r\\n], \"#\", \"=>\" at line 24, column 11 (byte 317) after filter {\n\tif ! [host][name] { \n\t\tmutate { \n\t\t\trename ", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:32:in `compile_imperative'", "org/logstash/execution/AbstractPipelineExt.java:187:in `initialize'", "org/logstash/execution/JavaBasePipelineExt.java:72:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:47:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:383:in `block in converge_state'"]}


[2022-01-18T20:52:02,049][WARN ][deprecation.logstash.codecs.plain] Relying on default value of `pipeline.ecs_compatibility`, which may change in a future major release of Logstash. To avoid unexpected changes when upgrading Logstash, please explicitly declare your desired ECS Compatibility mode.


[2022-01-18T20:52:02,107][WARN ][deprecation.logstash.codecs.plain] Relying on default value of `pipeline.ecs_compatibility`, which may change in a future major release of Logstash. To avoid unexpected changes when upgrading Logstash, please explicitly declare your desired ECS Compatibility mode.


[2022-01-18T20:52:02,168][WARN ][deprecation.logstash.outputs.elasticsearchmonitoring] Relying on default value of `pipeline.ecs_compatibility`, which may change in a future major release of Logstash. To avoid unexpected changes when upgrading Logstash, please explicitly declare your desired ECS Compatibility mode.


[2022-01-18T20:52:02,290][INFO ][logstash.outputs.elasticsearchmonitoring][.monitoring-logstash] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearchMonitoring", :hosts=>["http://elasticsearch:9200"]}


[2022-01-18T20:52:02,347][INFO ][logstash.outputs.elasticsearchmonitoring][.monitoring-logstash] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://elastic:xxxxxx@elasticsearch:9200/]}}


[2022-01-18T20:52:02,436][WARN ][logstash.outputs.elasticsearchmonitoring][.monitoring-logstash] Restored connection to ES instance {:url=>"http://elastic:xxxxxx@elasticsearch:9200/"}


[2022-01-18T20:52:02,450][INFO ][logstash.outputs.elasticsearchmonitoring][.monitoring-logstash] Elasticsearch version determined (7.16.2) {:es_version=>7}


[2022-01-18T20:52:02,452][WARN ][logstash.outputs.elasticsearchmonitoring][.monitoring-logstash] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}


[2022-01-18T20:52:02,573][WARN ][logstash.outputs.elasticsearchmonitoring][.monitoring-logstash] Configuration is data stream compliant but due backwards compatibility Logstash 7.x will not assume writing to a data-stream, default behavior will change on Logstash 8.0 (set `data_stream => true/false` to disable this warning)


[2022-01-18T20:52:02,599][WARN ][logstash.javapipeline    ][.monitoring-logstash] 'pipeline.ordered' is enabled and is likely less efficient, consider disabling if preserving event order is not necessary


[2022-01-18T20:52:02,728][INFO ][logstash.javapipeline    ][.monitoring-logstash] Starting pipeline {:pipeline_id=>".monitoring-logstash", "pipeline.workers"=>1, "pipeline.batch.size"=>2, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>2, "pipeline.sources"=>["monitoring pipeline"], :thread=>"#<Thread:0x1f10b92f@/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:54 run>"}


[2022-01-18T20:52:04,576][INFO ][logstash.javapipeline    ][.monitoring-logstash] Pipeline Java execution initialization time {"seconds"=>1.84}


[2022-01-18T20:52:04,659][INFO ][logstash.javapipeline    ][.monitoring-logstash] Pipeline started {"pipeline.id"=>".monitoring-logstash"}


[2022-01-18T20:52:06,556][INFO ][logstash.javapipeline    ][.monitoring-logstash] Pipeline terminated {"pipeline.id"=>".monitoring-logstash"}


[2022-01-18T20:52:07,165][INFO ][logstash.runner          ] Logstash shut down.
```

#### Docker setup

```console
$ docker version

Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

```console
$ docker-compose version

docker-compose version 1.26.2, build eefe0d31
docker-py version: 4.2.2
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

#### Container logs

```console
$ docker-compose logs

[docker-compose-logs.txt.zip](https://github.com/deviantony/docker-elk/files/7892449/docker-compose-logs.txt.zip)

```

**Comment by antoineco** [comment]
@nacesprin according to the logs you have a typo in your Logstash configuration

`"Expected one of [ \\t\\r\\n], \"#\", \"=>\" at line 24, column 11 (byte 317) after filter {\n\tif ! [host][name] { \n\t\tmutate { \n\t\t\trename "`

You didn't share your configuration so I can't tell you exactly what the typo is, but the error should hint at the line causing the error.

**Comment by nacesprin** [comment]
You was absolutely rigth. It was my unkownledgment

**Comment by antoineco** [comment]
Glad you figured it out!
