### ISSUE TITLE
TLS certificate instructions are not up-to-date and no longer work

### ISSUE THREAD

**Issue by gijs007** [deviantony/docker-elk#674]
The instructions regarding creating new TLS certificates, located at https://github.com/deviantony/docker-elk/blob/tls/tls/README.md are not up-to-date.

The instructions rely on an older version of Elastic Stack (7.17.0), instead of the latest (currently 8.0.0).
When executed the command with the specified 7.17.0 version, while using the latest Elastic Stack for the actual deployment, the user receives the following error:

`Exception in thread "main" java.nio.file.NoSuchFileException: /usr/share/elasticsearch/tls/instances.yml
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
        at java.base/java.nio.file.Files.newInputStream(Files.java:160)
        at java.base/java.nio.file.Files.newBufferedReader(Files.java:2922)
        at java.base/java.nio.file.Files.newBufferedReader(Files.java:2955)
        at org.elasticsearch.xpack.security.cli.CertificateTool.parseFile(CertificateTool.java:1013)
        at org.elasticsearch.xpack.security.cli.CertificateTool.parseAndValidateFile(CertificateTool.java:984)
        at org.elasticsearch.xpack.security.cli.CertificateTool$CertificateCommand.getCertificateInformationList(CertificateTool.java:421)
        at org.elasticsearch.xpack.security.cli.CertificateTool$GenerateCertificateCommand.execute(CertificateTool.java:722)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:95)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
        at org.elasticsearch.cli.Command.main(Command.java:77)
        at org.elasticsearch.xpack.security.cli.CertificateTool.main(CertificateTool.java:149)
`

**Comment by antoineco** [comment]
Ok, the image version wasn't updated, but the instructions still work (I tried).

I'll update the instructions to reflect the proper image version, but the process of generating TLS certificates is totally independent from the version of the running stack. The error you're seeing is probably due to something else, like the `tls/instances.yml` file not being mounted properly.

Could it be that the following warning was overlooked?

> **:warning: All commands assume you are inside the `tls` directory of the repository.**

**Comment by gijs007** [comment]
Thanks, I did overlook that warning which explains the error.

Note that when changing the version to 8.0.0 some other modifications are also required, as only changing the version will result in the following error: 
`Non-option arguments:
command              

Option             Description        
------             -----------        
-E <KeyValuePair>  Configure a setting
-h, --help         Show help          
-s, --silent       Show minimal output
-v, --verbose      Show verbose output

ERROR: Generating certificates without providing a CA is no longer supported.
Please first generate a CA with the 'ca' sub-command and provide the ca file 
with either --ca or --ca-cert/--ca-key to generate certificates.
`
