### ISSUE TITLE
Clean docker-compose up fails on ubuntu

### ISSUE THREAD

**Issue by BartlomiejLewandowski** [deviantony/docker-elk#702]
### Problem description

The stack fails to initialize properly,

#### Stack configuration

No additional configuration has been done.
#### Docker setup

Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```console
$ docker-compose version

docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

```

#### Container logs

```console
$ docker-compose logs


Attaching to docker-elk_setup_1
setup_1          | -------- Wed Apr 20 13:09:36 UTC 2022 --------
setup_1          | [+] Waiting for availability of Elasticsearch
setup_1          |    ⠿ Elasticsearch is running
setup_1          | [+] Role 'logstash_writer'
setup_1          |    ⠿ Creating/updating
docker-elk_setup_1 exited with code 28


lasticsearch_1  | {"@timestamp":"2022-04-20T13:10:36.229Z", "log.level":"ERROR", "message":"failed to put role [logstash_writer]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[c4a91192be69][generic][T#2]","log.logger":"org.elasticsearch.xpack.security.authz.store.NativeRolesStore","elasticsearch.cluster.uuid":"DFr1zpL3ReGXQp2W2X9zVA","elasticsearch.node.id":"72t2K_k1QFKRXt4NfSbScw","elasticsearch.node.name":"c4a91192be69","elasticsearch.cluster.name":"docker-cluster","error.type":"org.elasticsearch.action.UnavailableShardsException","error.message":"[.security-7][0] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[.security-7][0]] containing [index {[.security][role-logstash_writer], source[{\"cluster\":[\"manage_index_templates\",\"monitor\",\"manage_ilm\"],\"indices\":[{\"names\":[\"logs-generic-default\",\"logstash-*\",\"ecs-logstash-*\"],\"privileges\":[\"write\",\"create\",\"create_index\",\"manage\",\"manage_ilm\"],\"allow_restricted_indices\":false},{\"names\":[\"logstash\",\"ecs-logstash\"],\"privileges\":[\"write\",\"manage\"],\"allow_restricted_indices\":false}],\"applications\":[],\"run_as\":[],\"metadata\":{},\"type\":\"role\"}]}] and a refresh]","error.stack_trace":"org.elasticsearch.action.UnavailableShardsException: [.security-7][0] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[.security-7][0]] containing [index {[.security][role-logstash_writer], source[{\"cluster\":[\"manage_index_templates\",\"monitor\",\"manage_ilm\"],\"indices\":[{\"names\":[\"logs-generic-default\",\"logstash-*\",\"ecs-logstash-*\"],\"privileges\":[\"write\",\"create\",\"create_index\",\"manage\",\"manage_ilm\"],\"allow_restricted_indices\":false},{\"names\":[\"logstash\",\"ecs-logstash\"],\"privileges\":[\"write\",\"manage\"],\"allow_restricted_indices\":false}],\"applications\":[],\"run_as\":[],\"metadata\":{},\"type\":\"role\"}]}] and a refresh]\n\tat org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.retryBecauseUnavailable(TransportReplicationAction.java:1076)\n\tat org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.doRun(TransportReplicationAction.java:872)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)\n\tat org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$2.onTimeout(TransportReplicationAction.java:1031)\n\tat org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:345)\n\tat org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:263)\n\tat org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:651)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:717)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base/java.lang.Thread.run(Thread.java:833)\n"}


```

**Comment by antoineco** [comment]
@BartlomiejLewandowski thanks for the detailed issue report 🙌

It seems like there was a timing issue during the setup phase. Exit code `28` indicates that a client timeout occurred.
For some reason, the `setup` container didn't get an answer from Elasticsearch for 15 seconds and gave up without retrying. This is unexpected, we should definitely retry timeout errors.

Meanwhile, could you please verify whether retrying the setup with `docker-compose up setup` fixes the issue?

**Comment by antoineco** [comment]
OK, so the fact that `setup` doesn't retry on timeouts isn't the real issue here. If you retried manually and it's still failing, an automatic retry wouldn't solve your specific problem. (I'm not saying we shouldn't retry)

If Elasticsearch stops responding, or takes a very long time to respond, it means the Elasticsearch instance itself is facing some issues.

If I look at the error log, I see mentions of "UnavailableShardsException" and "primary shard is not active":

```
org.elasticsearch.action.UnavailableShardsException: [.security-7][0] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[.security-7][0]] containing [index {[.security][role-logstash_writer], source[{"cluster":["manage_index_templates","monitor","manage_ilm"],"indices":[{"names":["logs-generic-default","logstash-*","ecs-logstash-*"],"privileges":["write","create","create_index","manage","manage_ilm"],"allow_restricted_indices":false},{"names":["logstash","ecs-logstash"],"privileges":["write","manage"],"allow_restricted_indices":false}],"applications":[],"run_as":[],"metadata":{},"type":"role"}]}] and a refresh]
        at org.elasticsearch.action.support.replication.TransportReplicationAction.retryBecauseUnavailable(TransportReplicationAction.java:1076)
        at org.elasticsearch.action.support.replication.TransportReplicationAction.doRun(TransportReplicationAction.java:872)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at org.elasticsearch.action.support.replication.TransportReplicationAction.onTimeout(TransportReplicationAction.java:1031)
        at org.elasticsearch.cluster.ClusterStateObserver.onTimeout(ClusterStateObserver.java:345)
        at org.elasticsearch.cluster.ClusterStateObserver.onTimeout(ClusterStateObserver.java:263)
        at org.elasticsearch.cluster.service.ClusterApplierService.run(ClusterApplierService.java:651)
        at org.elasticsearch.common.util.concurrent.ThreadContext.run(ThreadContext.java:717)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

Using `docker-compose logs elasticsearch`, you'll most likely find other errors related to unavailable shards. Those would help finding the root cause of why Elasticsearch isn't healthy.

**Comment by antoineco** [comment]
Closing due to inactivity. Feel free to reopen if the issue is still relevant.
